/* A recursive-descent parser generated by peg 0.1.15 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#define YYRULECOUNT 38
#ifndef YY_MALLOC
#define YY_MALLOC(C, N)		malloc(N)
#endif
#ifndef YY_REALLOC
#define YY_REALLOC(C, P, N)	realloc(P, N)
#endif
#ifndef YY_FREE
#define YY_FREE(C, P)		free(P)
#endif
#ifndef YY_LOCAL
#define YY_LOCAL(T)	static T
#endif
#ifndef YY_ACTION
#define YY_ACTION(T)	static T
#endif
#ifndef YY_RULE
#define YY_RULE(T)	static T
#endif
#ifndef YY_PARSE
#define YY_PARSE(T)	T
#endif
#ifndef YYPARSE
#define YYPARSE		yyparse
#endif
#ifndef YYPARSEFROM
#define YYPARSEFROM	yyparsefrom
#endif
#ifndef YYRELEASE
#define YYRELEASE	yyrelease
#endif
#ifndef YY_BEGIN
#define YY_BEGIN	( yy->__begin= yy->__pos, 1)
#endif
#ifndef YY_END
#define YY_END		( yy->__end= yy->__pos, 1)
#endif
#ifdef YY_DEBUG
# define yyprintf(args)	fprintf args
#else
# define yyprintf(args)
#endif
#ifndef YYSTYPE
#define YYSTYPE	int
#endif
#ifndef YY_STACK_SIZE
#define YY_STACK_SIZE 128
#endif

#ifndef YY_BUFFER_SIZE
#define YY_BUFFER_SIZE 1024
#endif

#ifndef YY_PART

typedef struct _yycontext yycontext;
typedef void (*yyaction)(yycontext *yy, char *yytext, int yyleng);
typedef struct _yythunk { int begin, end;  yyaction  action;  struct _yythunk *next; } yythunk;

struct _yycontext {
  char     *__buf;
  int       __buflen;
  int       __pos;
  int       __limit;
  char     *__text;
  int       __textlen;
  int       __begin;
  int       __end;
  int       __textmax;
  yythunk  *__thunks;
  int       __thunkslen;
  int       __thunkpos;
  YYSTYPE   __;
  YYSTYPE  *__val;
  YYSTYPE  *__vals;
  int       __valslen;
#ifdef YY_CTX_MEMBERS
  YY_CTX_MEMBERS
#endif
};

#ifdef YY_CTX_LOCAL
#define YY_CTX_PARAM_	yycontext *yyctx,
#define YY_CTX_PARAM	yycontext *yyctx
#define YY_CTX_ARG_	yyctx,
#define YY_CTX_ARG	yyctx
#ifndef YY_INPUT
#define YY_INPUT(yy, buf, result, max_size)		\
  {							\
    int yyc= getchar();					\
    result= (EOF == yyc) ? 0 : (*(buf)= yyc, 1);	\
    yyprintf((stderr, "<%c>", yyc));			\
  }
#endif
#else
#define YY_CTX_PARAM_
#define YY_CTX_PARAM
#define YY_CTX_ARG_
#define YY_CTX_ARG
yycontext _yyctx= { 0, 0 };
yycontext *yyctx= &_yyctx;
#ifndef YY_INPUT
#define YY_INPUT(buf, result, max_size)			\
  {							\
    int yyc= getchar();					\
    result= (EOF == yyc) ? 0 : (*(buf)= yyc, 1);	\
    yyprintf((stderr, "<%c>", yyc));			\
  }
#endif
#endif

YY_LOCAL(int) yyrefill(yycontext *yy)
{
  int yyn;
  while (yy->__buflen - yy->__pos < 512)
    {
      yy->__buflen *= 2;
      yy->__buf= (char *)YY_REALLOC(yy, yy->__buf, yy->__buflen);
    }
#ifdef YY_CTX_LOCAL
  YY_INPUT(yy, (yy->__buf + yy->__pos), yyn, (yy->__buflen - yy->__pos));
#else
  YY_INPUT((yy->__buf + yy->__pos), yyn, (yy->__buflen - yy->__pos));
#endif
  if (!yyn) return 0;
  yy->__limit += yyn;
  return 1;
}

YY_LOCAL(int) yymatchDot(yycontext *yy)
{
  if (yy->__pos >= yy->__limit && !yyrefill(yy)) return 0;
  ++yy->__pos;
  return 1;
}

YY_LOCAL(int) yymatchChar(yycontext *yy, int c)
{
  if (yy->__pos >= yy->__limit && !yyrefill(yy)) return 0;
  if ((unsigned char)yy->__buf[yy->__pos] == c)
    {
      ++yy->__pos;
      yyprintf((stderr, "  ok   yymatchChar(yy, %c) @ %s\n", c, yy->__buf+yy->__pos));
      return 1;
    }
  yyprintf((stderr, "  fail yymatchChar(yy, %c) @ %s\n", c, yy->__buf+yy->__pos));
  return 0;
}

YY_LOCAL(int) yymatchString(yycontext *yy, const char *s)
{
  int yysav= yy->__pos;
  while (*s)
    {
      if (yy->__pos >= yy->__limit && !yyrefill(yy)) return 0;
      if (yy->__buf[yy->__pos] != *s)
        {
          yy->__pos= yysav;
          return 0;
        }
      ++s;
      ++yy->__pos;
    }
  return 1;
}

YY_LOCAL(int) yymatchClass(yycontext *yy, unsigned char *bits)
{
  int c;
  if (yy->__pos >= yy->__limit && !yyrefill(yy)) return 0;
  c= (unsigned char)yy->__buf[yy->__pos];
  if (bits[c >> 3] & (1 << (c & 7)))
    {
      ++yy->__pos;
      yyprintf((stderr, "  ok   yymatchClass @ %s\n", yy->__buf+yy->__pos));
      return 1;
    }
  yyprintf((stderr, "  fail yymatchClass @ %s\n", yy->__buf+yy->__pos));
  return 0;
}

YY_LOCAL(void) yyDo(yycontext *yy, yyaction action, int begin, int end)
{
  while (yy->__thunkpos >= yy->__thunkslen)
    {
      yy->__thunkslen *= 2;
      yy->__thunks= (yythunk *)YY_REALLOC(yy, yy->__thunks, sizeof(yythunk) * yy->__thunkslen);
    }
  yy->__thunks[yy->__thunkpos].begin=  begin;
  yy->__thunks[yy->__thunkpos].end=    end;
  yy->__thunks[yy->__thunkpos].action= action;
  ++yy->__thunkpos;
}

YY_LOCAL(int) yyText(yycontext *yy, int begin, int end)
{
  int yyleng= end - begin;
  if (yyleng <= 0)
    yyleng= 0;
  else
    {
      while (yy->__textlen < (yyleng + 1))
	{
	  yy->__textlen *= 2;
	  yy->__text= (char *)YY_REALLOC(yy, yy->__text, yy->__textlen);
	}
      memcpy(yy->__text, yy->__buf + begin, yyleng);
    }
  yy->__text[yyleng]= '\0';
  return yyleng;
}

YY_LOCAL(void) yyDone(yycontext *yy)
{
  int pos;
  for (pos= 0;  pos < yy->__thunkpos;  ++pos)
    {
      yythunk *thunk= &yy->__thunks[pos];
      int yyleng= thunk->end ? yyText(yy, thunk->begin, thunk->end) : thunk->begin;
      yyprintf((stderr, "DO [%d] %p %s\n", pos, thunk->action, yy->__text));
      thunk->action(yy, yy->__text, yyleng);
    }
  yy->__thunkpos= 0;
}

YY_LOCAL(void) yyCommit(yycontext *yy)
{
  if ((yy->__limit -= yy->__pos))
    {
      memmove(yy->__buf, yy->__buf + yy->__pos, yy->__limit);
    }
  yy->__begin -= yy->__pos;
  yy->__end -= yy->__pos;
  yy->__pos= yy->__thunkpos= 0;
}

YY_LOCAL(int) yyAccept(yycontext *yy, int tp0)
{
  if (tp0)
    {
      fprintf(stderr, "accept denied at %d\n", tp0);
      return 0;
    }
  else
    {
      yyDone(yy);
      yyCommit(yy);
    }
  return 1;
}

YY_LOCAL(void) yyPush(yycontext *yy, char *text, int count)
{
  yy->__val += count;
  while (yy->__valslen <= yy->__val - yy->__vals)
    {
      long offset= yy->__val - yy->__vals;
      yy->__valslen *= 2;
      yy->__vals= (YYSTYPE *)YY_REALLOC(yy, yy->__vals, sizeof(YYSTYPE) * yy->__valslen);
      yy->__val= yy->__vals + offset;
    }
}
YY_LOCAL(void) yyPop(yycontext *yy, char *text, int count)   { yy->__val -= count; }
YY_LOCAL(void) yySet(yycontext *yy, char *text, int count)   { yy->__val[count]= yy->__; }

#endif /* YY_PART */

#define	YYACCEPT	yyAccept(yy, yythunkpos0)

YY_RULE(int) yy_EscapedPCRE(yycontext *yy); /* 38 */
YY_RULE(int) yy_PCRE(yycontext *yy); /* 37 */
YY_RULE(int) yy_Value(yycontext *yy); /* 36 */
YY_RULE(int) yy_ValueList(yycontext *yy); /* 35 */
YY_RULE(int) yy_Digit(yycontext *yy); /* 34 */
YY_RULE(int) yy_ValueReference(yycontext *yy); /* 33 */
YY_RULE(int) yy_Dot(yycontext *yy); /* 32 */
YY_RULE(int) yy_OptDepends(yycontext *yy); /* 31 */
YY_RULE(int) yy_IfDepends(yycontext *yy); /* 30 */
YY_RULE(int) yy_Space(yycontext *yy); /* 29 */
YY_RULE(int) yy_TagReference(yycontext *yy); /* 28 */
YY_RULE(int) yy_Content(yycontext *yy); /* 27 */
YY_RULE(int) yy_Requirements(yycontext *yy); /* 26 */
YY_RULE(int) yy_Semicolon(yycontext *yy); /* 25 */
YY_RULE(int) yy_Tag(yycontext *yy); /* 24 */
YY_RULE(int) yy_Colon(yycontext *yy); /* 23 */
YY_RULE(int) yy_RegEx(yycontext *yy); /* 22 */
YY_RULE(int) yy_NTupel(yycontext *yy); /* 21 */
YY_RULE(int) yy_Number(yycontext *yy); /* 20 */
YY_RULE(int) yy_Only(yycontext *yy); /* 19 */
YY_RULE(int) yy_Range(yycontext *yy); /* 18 */
YY_RULE(int) yy_Any(yycontext *yy); /* 17 */
YY_RULE(int) yy_LogicalOrListElement(yycontext *yy); /* 16 */
YY_RULE(int) yy_LogicalOrList(yycontext *yy); /* 15 */
YY_RULE(int) yy_LogicalOr(yycontext *yy); /* 14 */
YY_RULE(int) yy_Mode(yycontext *yy); /* 13 */
YY_RULE(int) yy_ClosingBracket(yycontext *yy); /* 12 */
YY_RULE(int) yy_OpenBracket(yycontext *yy); /* 11 */
YY_RULE(int) yy_MiscUntilEOL(yycontext *yy); /* 10 */
YY_RULE(int) yy_TagLine(yycontext *yy); /* 9 */
YY_RULE(int) yy_IncludeLine(yycontext *yy); /* 8 */
YY_RULE(int) yy_ModeLine(yycontext *yy); /* 7 */
YY_RULE(int) yy_SpaceLine(yycontext *yy); /* 6 */
YY_RULE(int) yy_EndOfLine(yycontext *yy); /* 5 */
YY_RULE(int) yy_CommentLine(yycontext *yy); /* 4 */
YY_RULE(int) yy_EndOfFile(yycontext *yy); /* 3 */
YY_RULE(int) yy_Line(yycontext *yy); /* 2 */
YY_RULE(int) yy_start(yycontext *yy); /* 1 */

YY_ACTION(void) yy_1_EndOfLine(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_EndOfLine\n"));
  {
  incrlineno(); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_6_RegEx(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_6_RegEx\n"));
  {
   set_parse_error("'regex' expects an open bracket", yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_5_RegEx(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_5_RegEx\n"));
  {
   set_parse_error("'regex' expects an open '\"'", yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_4_RegEx(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_4_RegEx\n"));
  {
   set_parse_error("'regex' expects a PCRE-regex", yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_3_RegEx(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_3_RegEx\n"));
  {
   set_parse_error("'regex' expects a closing '\"'", yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_2_RegEx(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_RegEx\n"));
  {
   set_parse_error("'regex' expects a closing bracket", yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_RegEx(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_RegEx\n"));
  {
   regex_push ( yytext ); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_4_Only(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_4_Only\n"));
  {
   set_parse_error("'only' expects an open bracket", yytext);;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_3_Only(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_3_Only\n"));
  {
   set_parse_error("'only' expects a value list", yytext);;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_2_Only(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_Only\n"));
  {
   set_parse_error("'only' expects a closing bracket", yytext);;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_Only(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_Only\n"));
  {
    ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_7_ValueReference(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_7_ValueReference\n"));
  {
   set_parse_error("value reference error: '%s'", yytext);;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_6_ValueReference(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_6_ValueReference\n"));
  {
   parser_state.any_reference = only_ref; ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_5_ValueReference(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_5_ValueReference\n"));
  {
   parser_state.any_reference = ntupel_ref; ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_4_ValueReference(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_4_ValueReference\n"));
  {
   parser_state.any_reference = range_ref; ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_3_ValueReference(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_3_ValueReference\n"));
  {
   parser_state.any_reference = regex_ref; ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_2_ValueReference(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_ValueReference\n"));
  {
   parser_state.any_reference = only_ref; i_push(atol(yytext) );;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_ValueReference(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_ValueReference\n"));
  {
   parser_state.any_reference = any_ref; ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_4_NTupel(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_4_NTupel\n"));
  {
   set_parse_error("'ntupel' expects an open bracket", yytext);;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_3_NTupel(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_3_NTupel\n"));
  {
   set_parse_error("'ntupel' expects a value list", yytext);;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_2_NTupel(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_NTupel\n"));
  {
   set_parse_error("'ntupel' expects a closing bracket", yytext);;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_NTupel(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_NTupel\n"));
  {
  int v=parser_state.valuelist; i_push(v); reset_valuelist(); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_Value(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_Value\n"));
  {
   incr_values(); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_Dot(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_Dot\n"));
  {
   set_parse_error("missed dot", yytext);
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_Colon(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_Colon\n"));
  {
   set_parse_error("missed colon", yytext);;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_3_Number(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_3_Number\n"));
  {
   i_push(atol(yytext) );;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_2_Number(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_Number\n"));
  {
   i_push(2<<atol(yytext) ); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_Number(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_Number\n"));
  {
   i_push(strtol(yytext, NULL, 0) ); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_5_Range(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_5_Range\n"));
  {
   set_parse_error("'range' expects an open bracket", yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_4_Range(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_4_Range\n"));
  {
   set_parse_error("'range' expects a number", yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_3_Range(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_3_Range\n"));
  {
   set_parse_error("'range' expects a colon", yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_2_Range(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_Range\n"));
  {
   set_parse_error("'range' expects a number", yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_Range(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_Range\n"));
  {
   set_parse_error("'range' expects a closing bracket", yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_6_Content(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_6_Content\n"));
  {
   set_parse_error("wrong values-keyword", yytext);;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_5_Content(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_5_Content\n"));
  {
   v_push( regex ); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_4_Content(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_4_Content\n"));
  {
   v_push( ntupel ); reset_valuelist() ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_3_Content(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_3_Content\n"));
  {
   v_push( only ); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_2_Content(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_Content\n"));
  {
   v_push( range); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_Content(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_Content\n"));
  {
   v_push( any ); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_5_OptDepends(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_5_OptDepends\n"));
  {
   set_parse_error("'optdepends' expects an open bracket",  yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_4_OptDepends(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_4_OptDepends\n"));
  {
   set_parse_error("'optdepends' expects a tagreference",  yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_3_OptDepends(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_3_OptDepends\n"));
  {
   set_parse_error("'optdepends' expects a dot",  yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_2_OptDepends(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_OptDepends\n"));
  {
   set_parse_error("'optdepends' expects a value reference",  yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_OptDepends(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_OptDepends\n"));
  {
   set_parse_error("'optdepends' expects a closing bracket",  yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_5_IfDepends(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_5_IfDepends\n"));
  {
   set_parse_error("'depends' expects an open bracket",  yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_4_IfDepends(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_4_IfDepends\n"));
  {
   set_parse_error("'depends' expects a tagreference",  yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_3_IfDepends(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_3_IfDepends\n"));
  {
   set_parse_error("'depends' expects a dot",  yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_2_IfDepends(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_IfDepends\n"));
  {
   set_parse_error("'depends' expects a value reference",  yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_IfDepends(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_IfDepends\n"));
  {
   set_parse_error("'depends' expects a closing bracket",  yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_5_Requirements(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_5_Requirements\n"));
  {
   set_parse_error("wrong requirements-keyword", yytext);;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_4_Requirements(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_4_Requirements\n"));
  {
   set_optional(); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_3_Requirements(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_3_Requirements\n"));
  {
   set_optdepends(); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_2_Requirements(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_Requirements\n"));
  {
   set_ifdepends(); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_Requirements(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_Requirements\n"));
  {
   set_mandatory(); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_Semicolon(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_Semicolon\n"));
  {
   set_parse_error("missed semicolon", yytext);;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_2_TagReference(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_TagReference\n"));
  {
   set_parse_error("wrong tagreference", yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_TagReference(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_TagReference\n"));
  {
  
                        int tag = i_pop();
                        if (tag < 254) set_parse_error("wrong tagreference (should be >253)", yytext);
                        else if (tag > 65535) set_parse_error("wrong tagreference (should be <65536)", yytext);
                        else settagref( tag );
                ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_Tag(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_Tag\n"));
  {
  
                        int tag = i_pop();
                        /* rule_tagorder_in_dsl( tag ); */
                        if (tag < 254) set_parse_error("wrong tag (should be >253)", yytext);
                        else if (tag > 65535) set_parse_error("wrong tag (should be <65536)", yytext);
                        else settag( tag );
                ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_5_TagLine(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_5_TagLine\n"));
  {
   set_parse_error("tagline expects missed semicolon here", yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_4_TagLine(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_4_TagLine\n"));
  {
   set_parse_error("tagline requires a requiemrent-keyword (mandatory, etc.)",yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_3_TagLine(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_3_TagLine\n"));
  {
   set_parse_error("tagline expects missed semicolon here", yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_2_TagLine(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_TagLine\n"));
  {
   set_parse_error("tagline requires content", yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_TagLine(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_TagLine\n"));
  {
   rule_addtag_config();  ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_Mode(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_Mode\n"));
  {
   set_parse_error("mode expects either 'baseline' or 'enhanced'", yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_7_LogicalOrListElement(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_7_LogicalOrListElement\n"));
  {
   set_parse_error("wrong values-keyword", yytext);;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_6_LogicalOrListElement(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_6_LogicalOrListElement\n"));
  {
   v_push( regex );incr_logical_elements();  ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_5_LogicalOrListElement(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_5_LogicalOrListElement\n"));
  {
   v_push( ntupel); reset_valuelist(); incr_logical_elements(); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_4_LogicalOrListElement(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_4_LogicalOrListElement\n"));
  {
   v_push( only );incr_logical_elements();  ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_3_LogicalOrListElement(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_3_LogicalOrListElement\n"));
  {
   v_push( only );incr_logical_elements();  ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_2_LogicalOrListElement(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_LogicalOrListElement\n"));
  {
   v_push( range);incr_logical_elements();  ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_LogicalOrListElement(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_LogicalOrListElement\n"));
  {
   v_push( any );incr_logical_elements(); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_LogicalOr(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_LogicalOr\n"));
  {
   rule_add_logical_config(); reset_logical_list();;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_4_ModeLine(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_4_ModeLine\n"));
  {
   set_parse_error( "modeline requires an open bracket", yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_3_ModeLine(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_3_ModeLine\n"));
  {
   set_parse_error( "modeline requires a mode", yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_2_ModeLine(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_ModeLine\n"));
  {
   set_parse_error( "modeline expects a closing bracket", yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_ModeLine(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_ModeLine\n"));
  {
   set_mode( yytext );  ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_IncludeLine(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_IncludeLine\n"));
  {
   set_include ( yytext );  ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_CommentLine(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_CommentLine\n"));
  {
   commentline(); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_Line(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_Line\n"));
  {
   set_parse_error("wrong line entry",yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}

YY_RULE(int) yy_EscapedPCRE(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "EscapedPCRE"));
  {  int yypos2= yy->__pos, yythunkpos2= yy->__thunkpos;  if (!yymatchChar(yy, '\\')) goto l3;  if (!yymatchChar(yy, '\\')) goto l3;  goto l2;
  l3:;	  yy->__pos= yypos2; yy->__thunkpos= yythunkpos2;  if (!yymatchChar(yy, '\\')) goto l1;  if (!yymatchChar(yy, '"')) goto l1;
  }
  l2:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "EscapedPCRE", yy->__buf+yy->__pos));
  return 1;
  l1:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "EscapedPCRE", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_PCRE(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "PCRE"));
  {  int yypos5= yy->__pos, yythunkpos5= yy->__thunkpos;  if (!yy_EscapedPCRE(yy)) goto l6;  goto l5;
  l6:;	  yy->__pos= yypos5; yy->__thunkpos= yythunkpos5;  if (!yymatchClass(yy, (unsigned char *)"\377\377\377\377\373\377\377\377\377\377\377\357\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377")) goto l4;
  }
  l5:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "PCRE", yy->__buf+yy->__pos));
  return 1;
  l4:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "PCRE", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_Value(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "Value"));  if (!yy_Number(yy)) goto l7;  yyDo(yy, yy_1_Value, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "Value", yy->__buf+yy->__pos));
  return 1;
  l7:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Value", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_ValueList(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "ValueList"));  if (!yy_Value(yy)) goto l8;
  l9:;	
  {  int yypos10= yy->__pos, yythunkpos10= yy->__thunkpos;  if (!yy_Colon(yy)) goto l10;  if (!yy_Value(yy)) goto l10;  goto l9;
  l10:;	  yy->__pos= yypos10; yy->__thunkpos= yythunkpos10;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "ValueList", yy->__buf+yy->__pos));
  return 1;
  l8:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "ValueList", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_Digit(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "Digit"));  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l11;
  yyprintf((stderr, "  ok   %s @ %s\n", "Digit", yy->__buf+yy->__pos));
  return 1;
  l11:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Digit", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_ValueReference(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "ValueReference"));
  {  int yypos13= yy->__pos, yythunkpos13= yy->__thunkpos;  if (!yy_Any(yy)) goto l14;  yyDo(yy, yy_1_ValueReference, yy->__begin, yy->__end);  goto l13;
  l14:;	  yy->__pos= yypos13; yy->__thunkpos= yythunkpos13;  if (!yy_Number(yy)) goto l15;  yyDo(yy, yy_2_ValueReference, yy->__begin, yy->__end);  goto l13;
  l15:;	  yy->__pos= yypos13; yy->__thunkpos= yythunkpos13;  if (!yy_RegEx(yy)) goto l16;  yyDo(yy, yy_3_ValueReference, yy->__begin, yy->__end);  goto l13;
  l16:;	  yy->__pos= yypos13; yy->__thunkpos= yythunkpos13;  if (!yy_Range(yy)) goto l17;  yyDo(yy, yy_4_ValueReference, yy->__begin, yy->__end);  goto l13;
  l17:;	  yy->__pos= yypos13; yy->__thunkpos= yythunkpos13;  if (!yy_NTupel(yy)) goto l18;  yyDo(yy, yy_5_ValueReference, yy->__begin, yy->__end);  goto l13;
  l18:;	  yy->__pos= yypos13; yy->__thunkpos= yythunkpos13;  if (!yy_Only(yy)) goto l19;  yyDo(yy, yy_6_ValueReference, yy->__begin, yy->__end);  goto l13;
  l19:;	  yy->__pos= yypos13; yy->__thunkpos= yythunkpos13;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l12;
#undef yytext
#undef yyleng
  }  if (!yy_MiscUntilEOL(yy)) goto l12;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l12;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_7_ValueReference, yy->__begin, yy->__end);
  }
  l13:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "ValueReference", yy->__buf+yy->__pos));
  return 1;
  l12:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "ValueReference", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_Dot(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "Dot"));
  {  int yypos21= yy->__pos, yythunkpos21= yy->__thunkpos;  if (!yymatchChar(yy, '.')) goto l22;
  l23:;	
  {  int yypos24= yy->__pos, yythunkpos24= yy->__thunkpos;  if (!yy_Space(yy)) goto l24;  goto l23;
  l24:;	  yy->__pos= yypos24; yy->__thunkpos= yythunkpos24;
  }  goto l21;
  l22:;	  yy->__pos= yypos21; yy->__thunkpos= yythunkpos21;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l20;
#undef yytext
#undef yyleng
  }  if (!yy_MiscUntilEOL(yy)) goto l20;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l20;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_1_Dot, yy->__begin, yy->__end);
  }
  l21:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "Dot", yy->__buf+yy->__pos));
  return 1;
  l20:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Dot", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_OptDepends(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "OptDepends"));
  {  int yypos26= yy->__pos, yythunkpos26= yy->__thunkpos;  if (!yymatchString(yy, "optdepends")) goto l27;  if (!yy_OpenBracket(yy)) goto l27;  if (!yy_TagReference(yy)) goto l27;  if (!yy_Dot(yy)) goto l27;  if (!yy_ValueReference(yy)) goto l27;  if (!yy_ClosingBracket(yy)) goto l27;  goto l26;
  l27:;	  yy->__pos= yypos26; yy->__thunkpos= yythunkpos26;  if (!yymatchString(yy, "optdepends")) goto l28;  if (!yy_OpenBracket(yy)) goto l28;  if (!yy_TagReference(yy)) goto l28;  if (!yy_Dot(yy)) goto l28;  if (!yy_ValueReference(yy)) goto l28;  yyDo(yy, yy_1_OptDepends, yy->__begin, yy->__end);  goto l26;
  l28:;	  yy->__pos= yypos26; yy->__thunkpos= yythunkpos26;  if (!yymatchString(yy, "optdepends")) goto l29;  if (!yy_OpenBracket(yy)) goto l29;  if (!yy_TagReference(yy)) goto l29;  if (!yy_Dot(yy)) goto l29;  yyDo(yy, yy_2_OptDepends, yy->__begin, yy->__end);  goto l26;
  l29:;	  yy->__pos= yypos26; yy->__thunkpos= yythunkpos26;  if (!yymatchString(yy, "optdepends")) goto l30;  if (!yy_OpenBracket(yy)) goto l30;  if (!yy_TagReference(yy)) goto l30;  yyDo(yy, yy_3_OptDepends, yy->__begin, yy->__end);  goto l26;
  l30:;	  yy->__pos= yypos26; yy->__thunkpos= yythunkpos26;  if (!yymatchString(yy, "optdepends")) goto l31;  if (!yy_OpenBracket(yy)) goto l31;  yyDo(yy, yy_4_OptDepends, yy->__begin, yy->__end);  goto l26;
  l31:;	  yy->__pos= yypos26; yy->__thunkpos= yythunkpos26;  if (!yymatchString(yy, "optdepends")) goto l25;  yyDo(yy, yy_5_OptDepends, yy->__begin, yy->__end);
  }
  l26:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "OptDepends", yy->__buf+yy->__pos));
  return 1;
  l25:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "OptDepends", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_IfDepends(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "IfDepends"));
  {  int yypos33= yy->__pos, yythunkpos33= yy->__thunkpos;  if (!yymatchString(yy, "depends")) goto l34;  if (!yy_OpenBracket(yy)) goto l34;  if (!yy_TagReference(yy)) goto l34;  if (!yy_Dot(yy)) goto l34;  if (!yy_ValueReference(yy)) goto l34;  if (!yy_ClosingBracket(yy)) goto l34;  goto l33;
  l34:;	  yy->__pos= yypos33; yy->__thunkpos= yythunkpos33;  if (!yymatchString(yy, "depends")) goto l35;  if (!yy_OpenBracket(yy)) goto l35;  if (!yy_TagReference(yy)) goto l35;  if (!yy_Dot(yy)) goto l35;  if (!yy_ValueReference(yy)) goto l35;  yyDo(yy, yy_1_IfDepends, yy->__begin, yy->__end);  goto l33;
  l35:;	  yy->__pos= yypos33; yy->__thunkpos= yythunkpos33;  if (!yymatchString(yy, "depends")) goto l36;  if (!yy_OpenBracket(yy)) goto l36;  if (!yy_TagReference(yy)) goto l36;  if (!yy_Dot(yy)) goto l36;  yyDo(yy, yy_2_IfDepends, yy->__begin, yy->__end);  goto l33;
  l36:;	  yy->__pos= yypos33; yy->__thunkpos= yythunkpos33;  if (!yymatchString(yy, "depends")) goto l37;  if (!yy_OpenBracket(yy)) goto l37;  if (!yy_TagReference(yy)) goto l37;  yyDo(yy, yy_3_IfDepends, yy->__begin, yy->__end);  goto l33;
  l37:;	  yy->__pos= yypos33; yy->__thunkpos= yythunkpos33;  if (!yymatchString(yy, "depends")) goto l38;  if (!yy_OpenBracket(yy)) goto l38;  yyDo(yy, yy_4_IfDepends, yy->__begin, yy->__end);  goto l33;
  l38:;	  yy->__pos= yypos33; yy->__thunkpos= yythunkpos33;  if (!yymatchString(yy, "depends")) goto l32;  yyDo(yy, yy_5_IfDepends, yy->__begin, yy->__end);
  }
  l33:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "IfDepends", yy->__buf+yy->__pos));
  return 1;
  l32:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "IfDepends", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_Space(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "Space"));
  {  int yypos40= yy->__pos, yythunkpos40= yy->__thunkpos;  if (!yymatchChar(yy, ' ')) goto l41;  goto l40;
  l41:;	  yy->__pos= yypos40; yy->__thunkpos= yythunkpos40;  if (!yymatchChar(yy, '\t')) goto l39;
  }
  l40:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "Space", yy->__buf+yy->__pos));
  return 1;
  l39:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Space", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_TagReference(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "TagReference"));
  {  int yypos43= yy->__pos, yythunkpos43= yy->__thunkpos;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l44;
#undef yytext
#undef yyleng
  }  if (!yy_Number(yy)) goto l44;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l44;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_1_TagReference, yy->__begin, yy->__end);  goto l43;
  l44:;	  yy->__pos= yypos43; yy->__thunkpos= yythunkpos43;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l42;
#undef yytext
#undef yyleng
  }  if (!yy_MiscUntilEOL(yy)) goto l42;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l42;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_2_TagReference, yy->__begin, yy->__end);
  }
  l43:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "TagReference", yy->__buf+yy->__pos));
  return 1;
  l42:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "TagReference", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_Content(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "Content"));
  {  int yypos46= yy->__pos, yythunkpos46= yy->__thunkpos;  if (!yy_Any(yy)) goto l47;  yyDo(yy, yy_1_Content, yy->__begin, yy->__end);  goto l46;
  l47:;	  yy->__pos= yypos46; yy->__thunkpos= yythunkpos46;  if (!yy_Range(yy)) goto l48;  yyDo(yy, yy_2_Content, yy->__begin, yy->__end);  goto l46;
  l48:;	  yy->__pos= yypos46; yy->__thunkpos= yythunkpos46;  if (!yy_LogicalOr(yy)) goto l49;  goto l46;
  l49:;	  yy->__pos= yypos46; yy->__thunkpos= yythunkpos46;  if (!yy_Only(yy)) goto l50;  yyDo(yy, yy_3_Content, yy->__begin, yy->__end);  goto l46;
  l50:;	  yy->__pos= yypos46; yy->__thunkpos= yythunkpos46;  if (!yy_NTupel(yy)) goto l51;  yyDo(yy, yy_4_Content, yy->__begin, yy->__end);  goto l46;
  l51:;	  yy->__pos= yypos46; yy->__thunkpos= yythunkpos46;  if (!yy_RegEx(yy)) goto l52;  yyDo(yy, yy_5_Content, yy->__begin, yy->__end);  goto l46;
  l52:;	  yy->__pos= yypos46; yy->__thunkpos= yythunkpos46;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l45;
#undef yytext
#undef yyleng
  }  if (!yy_MiscUntilEOL(yy)) goto l45;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l45;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_6_Content, yy->__begin, yy->__end);
  }
  l46:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "Content", yy->__buf+yy->__pos));
  return 1;
  l45:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Content", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_Requirements(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "Requirements"));
  {  int yypos54= yy->__pos, yythunkpos54= yy->__thunkpos;  if (!yymatchString(yy, "mandatory")) goto l55;  yyDo(yy, yy_1_Requirements, yy->__begin, yy->__end);  goto l54;
  l55:;	  yy->__pos= yypos54; yy->__thunkpos= yythunkpos54;  if (!yy_IfDepends(yy)) goto l56;  yyDo(yy, yy_2_Requirements, yy->__begin, yy->__end);  goto l54;
  l56:;	  yy->__pos= yypos54; yy->__thunkpos= yythunkpos54;  if (!yy_OptDepends(yy)) goto l57;  yyDo(yy, yy_3_Requirements, yy->__begin, yy->__end);  goto l54;
  l57:;	  yy->__pos= yypos54; yy->__thunkpos= yythunkpos54;  if (!yymatchString(yy, "optional")) goto l58;  yyDo(yy, yy_4_Requirements, yy->__begin, yy->__end);  goto l54;
  l58:;	  yy->__pos= yypos54; yy->__thunkpos= yythunkpos54;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l53;
#undef yytext
#undef yyleng
  }  if (!yy_MiscUntilEOL(yy)) goto l53;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l53;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_5_Requirements, yy->__begin, yy->__end);
  }
  l54:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "Requirements", yy->__buf+yy->__pos));
  return 1;
  l53:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Requirements", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_Semicolon(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "Semicolon"));
  {  int yypos60= yy->__pos, yythunkpos60= yy->__thunkpos;  if (!yymatchChar(yy, ';')) goto l61;
  l62:;	
  {  int yypos63= yy->__pos, yythunkpos63= yy->__thunkpos;  if (!yy_Space(yy)) goto l63;  goto l62;
  l63:;	  yy->__pos= yypos63; yy->__thunkpos= yythunkpos63;
  }  goto l60;
  l61:;	  yy->__pos= yypos60; yy->__thunkpos= yythunkpos60;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l59;
#undef yytext
#undef yyleng
  }  if (!yy_MiscUntilEOL(yy)) goto l59;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l59;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_1_Semicolon, yy->__begin, yy->__end);
  }
  l60:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "Semicolon", yy->__buf+yy->__pos));
  return 1;
  l59:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Semicolon", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_Tag(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "Tag"));  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l64;
#undef yytext
#undef yyleng
  }  if (!yy_Number(yy)) goto l64;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l64;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_1_Tag, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "Tag", yy->__buf+yy->__pos));
  return 1;
  l64:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Tag", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_Colon(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "Colon"));
  {  int yypos66= yy->__pos, yythunkpos66= yy->__thunkpos;  if (!yymatchChar(yy, ',')) goto l67;
  l68:;	
  {  int yypos69= yy->__pos, yythunkpos69= yy->__thunkpos;  if (!yy_Space(yy)) goto l69;  goto l68;
  l69:;	  yy->__pos= yypos69; yy->__thunkpos= yythunkpos69;
  }  goto l66;
  l67:;	  yy->__pos= yypos66; yy->__thunkpos= yythunkpos66;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l65;
#undef yytext
#undef yyleng
  }  if (!yy_MiscUntilEOL(yy)) goto l65;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l65;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_1_Colon, yy->__begin, yy->__end);
  }
  l66:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "Colon", yy->__buf+yy->__pos));
  return 1;
  l65:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Colon", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_RegEx(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "RegEx"));
  {  int yypos71= yy->__pos, yythunkpos71= yy->__thunkpos;  if (!yymatchString(yy, "regex")) goto l72;  if (!yy_OpenBracket(yy)) goto l72;  if (!yymatchChar(yy, '"')) goto l72;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l72;
#undef yytext
#undef yyleng
  }
  l73:;	
  {  int yypos74= yy->__pos, yythunkpos74= yy->__thunkpos;  if (!yy_PCRE(yy)) goto l74;  goto l73;
  l74:;	  yy->__pos= yypos74; yy->__thunkpos= yythunkpos74;
  }  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l72;
#undef yytext
#undef yyleng
  }  if (!yymatchChar(yy, '"')) goto l72;  if (!yy_ClosingBracket(yy)) goto l72;  yyDo(yy, yy_1_RegEx, yy->__begin, yy->__end);  goto l71;
  l72:;	  yy->__pos= yypos71; yy->__thunkpos= yythunkpos71;  if (!yymatchString(yy, "regex")) goto l75;  if (!yy_OpenBracket(yy)) goto l75;  if (!yymatchChar(yy, '"')) goto l75;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l75;
#undef yytext
#undef yyleng
  }
  l76:;	
  {  int yypos77= yy->__pos, yythunkpos77= yy->__thunkpos;  if (!yy_PCRE(yy)) goto l77;  goto l76;
  l77:;	  yy->__pos= yypos77; yy->__thunkpos= yythunkpos77;
  }  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l75;
#undef yytext
#undef yyleng
  }  if (!yymatchChar(yy, '"')) goto l75;  yyDo(yy, yy_2_RegEx, yy->__begin, yy->__end);  goto l71;
  l75:;	  yy->__pos= yypos71; yy->__thunkpos= yythunkpos71;  if (!yymatchString(yy, "regex")) goto l78;  if (!yy_OpenBracket(yy)) goto l78;  if (!yymatchChar(yy, '"')) goto l78;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l78;
#undef yytext
#undef yyleng
  }
  l79:;	
  {  int yypos80= yy->__pos, yythunkpos80= yy->__thunkpos;  if (!yy_PCRE(yy)) goto l80;  goto l79;
  l80:;	  yy->__pos= yypos80; yy->__thunkpos= yythunkpos80;
  }  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l78;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_3_RegEx, yy->__begin, yy->__end);  goto l71;
  l78:;	  yy->__pos= yypos71; yy->__thunkpos= yythunkpos71;  if (!yymatchString(yy, "regex")) goto l81;  if (!yy_OpenBracket(yy)) goto l81;  if (!yymatchChar(yy, '"')) goto l81;  yyDo(yy, yy_4_RegEx, yy->__begin, yy->__end);  goto l71;
  l81:;	  yy->__pos= yypos71; yy->__thunkpos= yythunkpos71;  if (!yymatchString(yy, "regex")) goto l82;  if (!yy_OpenBracket(yy)) goto l82;  yyDo(yy, yy_5_RegEx, yy->__begin, yy->__end);  goto l71;
  l82:;	  yy->__pos= yypos71; yy->__thunkpos= yythunkpos71;  if (!yymatchString(yy, "regex")) goto l70;  yyDo(yy, yy_6_RegEx, yy->__begin, yy->__end);
  }
  l71:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "RegEx", yy->__buf+yy->__pos));
  return 1;
  l70:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "RegEx", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_NTupel(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "NTupel"));
  {  int yypos84= yy->__pos, yythunkpos84= yy->__thunkpos;  if (!yymatchString(yy, "ntupel")) goto l85;  if (!yy_OpenBracket(yy)) goto l85;  if (!yy_ValueList(yy)) goto l85;  if (!yy_ClosingBracket(yy)) goto l85;  yyDo(yy, yy_1_NTupel, yy->__begin, yy->__end);  goto l84;
  l85:;	  yy->__pos= yypos84; yy->__thunkpos= yythunkpos84;  if (!yymatchString(yy, "ntupel")) goto l86;  if (!yy_OpenBracket(yy)) goto l86;  if (!yy_ValueList(yy)) goto l86;  yyDo(yy, yy_2_NTupel, yy->__begin, yy->__end);  goto l84;
  l86:;	  yy->__pos= yypos84; yy->__thunkpos= yythunkpos84;  if (!yymatchString(yy, "ntupel")) goto l87;  if (!yy_OpenBracket(yy)) goto l87;  yyDo(yy, yy_3_NTupel, yy->__begin, yy->__end);  goto l84;
  l87:;	  yy->__pos= yypos84; yy->__thunkpos= yythunkpos84;  if (!yymatchString(yy, "ntupel")) goto l83;  yyDo(yy, yy_4_NTupel, yy->__begin, yy->__end);
  }
  l84:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "NTupel", yy->__buf+yy->__pos));
  return 1;
  l83:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "NTupel", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_Number(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "Number"));
  {  int yypos89= yy->__pos, yythunkpos89= yy->__thunkpos;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l90;
#undef yytext
#undef yyleng
  }  if (!yymatchString(yy, "0x")) goto l90;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\176\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l90;
  l91:;	
  {  int yypos92= yy->__pos, yythunkpos92= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\176\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l92;  goto l91;
  l92:;	  yy->__pos= yypos92; yy->__thunkpos= yythunkpos92;
  }  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l90;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_1_Number, yy->__begin, yy->__end);  goto l89;
  l90:;	  yy->__pos= yypos89; yy->__thunkpos= yythunkpos89;  if (!yymatchString(yy, "2^")) goto l93;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l93;
#undef yytext
#undef yyleng
  }  if (!yy_Digit(yy)) goto l93;
  l94:;	
  {  int yypos95= yy->__pos, yythunkpos95= yy->__thunkpos;  if (!yy_Digit(yy)) goto l95;  goto l94;
  l95:;	  yy->__pos= yypos95; yy->__thunkpos= yythunkpos95;
  }  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l93;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_2_Number, yy->__begin, yy->__end);  goto l89;
  l93:;	  yy->__pos= yypos89; yy->__thunkpos= yythunkpos89;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l88;
#undef yytext
#undef yyleng
  }  if (!yy_Digit(yy)) goto l88;
  l96:;	
  {  int yypos97= yy->__pos, yythunkpos97= yy->__thunkpos;  if (!yy_Digit(yy)) goto l97;  goto l96;
  l97:;	  yy->__pos= yypos97; yy->__thunkpos= yythunkpos97;
  }  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l88;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_3_Number, yy->__begin, yy->__end);
  }
  l89:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "Number", yy->__buf+yy->__pos));
  return 1;
  l88:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Number", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_Only(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "Only"));
  {  int yypos99= yy->__pos, yythunkpos99= yy->__thunkpos;  if (!yymatchString(yy, "only")) goto l100;  if (!yy_OpenBracket(yy)) goto l100;  if (!yy_Number(yy)) goto l100;  if (!yy_ClosingBracket(yy)) goto l100;  yyDo(yy, yy_1_Only, yy->__begin, yy->__end);  goto l99;
  l100:;	  yy->__pos= yypos99; yy->__thunkpos= yythunkpos99;  if (!yymatchString(yy, "only")) goto l101;  if (!yy_OpenBracket(yy)) goto l101;  if (!yy_Number(yy)) goto l101;  yyDo(yy, yy_2_Only, yy->__begin, yy->__end);  goto l99;
  l101:;	  yy->__pos= yypos99; yy->__thunkpos= yythunkpos99;  if (!yymatchString(yy, "only")) goto l102;  if (!yy_OpenBracket(yy)) goto l102;  yyDo(yy, yy_3_Only, yy->__begin, yy->__end);  goto l99;
  l102:;	  yy->__pos= yypos99; yy->__thunkpos= yythunkpos99;  if (!yymatchString(yy, "only")) goto l98;  yyDo(yy, yy_4_Only, yy->__begin, yy->__end);
  }
  l99:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "Only", yy->__buf+yy->__pos));
  return 1;
  l98:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Only", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_Range(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "Range"));
  {  int yypos104= yy->__pos, yythunkpos104= yy->__thunkpos;  if (!yymatchString(yy, "range")) goto l105;  if (!yy_OpenBracket(yy)) goto l105;  if (!yy_Number(yy)) goto l105;  if (!yy_Colon(yy)) goto l105;  if (!yy_Number(yy)) goto l105;  if (!yy_ClosingBracket(yy)) goto l105;  goto l104;
  l105:;	  yy->__pos= yypos104; yy->__thunkpos= yythunkpos104;  if (!yymatchString(yy, "range")) goto l106;  if (!yy_OpenBracket(yy)) goto l106;  if (!yy_Number(yy)) goto l106;  if (!yy_Colon(yy)) goto l106;  if (!yy_Number(yy)) goto l106;  yyDo(yy, yy_1_Range, yy->__begin, yy->__end);  goto l104;
  l106:;	  yy->__pos= yypos104; yy->__thunkpos= yythunkpos104;  if (!yymatchString(yy, "range")) goto l107;  if (!yy_OpenBracket(yy)) goto l107;  if (!yy_Number(yy)) goto l107;  if (!yy_Colon(yy)) goto l107;  yyDo(yy, yy_2_Range, yy->__begin, yy->__end);  goto l104;
  l107:;	  yy->__pos= yypos104; yy->__thunkpos= yythunkpos104;  if (!yymatchString(yy, "range")) goto l108;  if (!yy_OpenBracket(yy)) goto l108;  if (!yy_Number(yy)) goto l108;  yyDo(yy, yy_3_Range, yy->__begin, yy->__end);  goto l104;
  l108:;	  yy->__pos= yypos104; yy->__thunkpos= yythunkpos104;  if (!yymatchString(yy, "range")) goto l109;  if (!yy_OpenBracket(yy)) goto l109;  yyDo(yy, yy_4_Range, yy->__begin, yy->__end);  goto l104;
  l109:;	  yy->__pos= yypos104; yy->__thunkpos= yythunkpos104;  if (!yymatchString(yy, "range")) goto l103;  yyDo(yy, yy_5_Range, yy->__begin, yy->__end);
  }
  l104:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "Range", yy->__buf+yy->__pos));
  return 1;
  l103:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Range", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_Any(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "Any"));  if (!yymatchString(yy, "any")) goto l110;
  yyprintf((stderr, "  ok   %s @ %s\n", "Any", yy->__buf+yy->__pos));
  return 1;
  l110:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Any", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_LogicalOrListElement(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "LogicalOrListElement"));
  {  int yypos112= yy->__pos, yythunkpos112= yy->__thunkpos;  if (!yy_Any(yy)) goto l113;  yyDo(yy, yy_1_LogicalOrListElement, yy->__begin, yy->__end);  goto l112;
  l113:;	  yy->__pos= yypos112; yy->__thunkpos= yythunkpos112;  if (!yy_Range(yy)) goto l114;  yyDo(yy, yy_2_LogicalOrListElement, yy->__begin, yy->__end);  goto l112;
  l114:;	  yy->__pos= yypos112; yy->__thunkpos= yythunkpos112;  if (!yy_Only(yy)) goto l115;  yyDo(yy, yy_3_LogicalOrListElement, yy->__begin, yy->__end);  goto l112;
  l115:;	  yy->__pos= yypos112; yy->__thunkpos= yythunkpos112;  if (!yy_Number(yy)) goto l116;  yyDo(yy, yy_4_LogicalOrListElement, yy->__begin, yy->__end);  goto l112;
  l116:;	  yy->__pos= yypos112; yy->__thunkpos= yythunkpos112;  if (!yy_NTupel(yy)) goto l117;  yyDo(yy, yy_5_LogicalOrListElement, yy->__begin, yy->__end);  goto l112;
  l117:;	  yy->__pos= yypos112; yy->__thunkpos= yythunkpos112;  if (!yy_RegEx(yy)) goto l118;  yyDo(yy, yy_6_LogicalOrListElement, yy->__begin, yy->__end);  goto l112;
  l118:;	  yy->__pos= yypos112; yy->__thunkpos= yythunkpos112;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l111;
#undef yytext
#undef yyleng
  }  if (!yy_MiscUntilEOL(yy)) goto l111;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l111;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_7_LogicalOrListElement, yy->__begin, yy->__end);
  }
  l112:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "LogicalOrListElement", yy->__buf+yy->__pos));
  return 1;
  l111:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "LogicalOrListElement", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_LogicalOrList(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "LogicalOrList"));  if (!yy_LogicalOrListElement(yy)) goto l119;
  l120:;	
  {  int yypos121= yy->__pos, yythunkpos121= yy->__thunkpos;  if (!yy_Colon(yy)) goto l121;  if (!yy_LogicalOrListElement(yy)) goto l121;  goto l120;
  l121:;	  yy->__pos= yypos121; yy->__thunkpos= yythunkpos121;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "LogicalOrList", yy->__buf+yy->__pos));
  return 1;
  l119:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "LogicalOrList", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_LogicalOr(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "LogicalOr"));  if (!yymatchString(yy, "logical_or")) goto l122;  if (!yy_OpenBracket(yy)) goto l122;  if (!yy_LogicalOrList(yy)) goto l122;  if (!yy_ClosingBracket(yy)) goto l122;  yyDo(yy, yy_1_LogicalOr, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "LogicalOr", yy->__buf+yy->__pos));
  return 1;
  l122:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "LogicalOr", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_Mode(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "Mode"));
  {  int yypos124= yy->__pos, yythunkpos124= yy->__thunkpos;  if (!yymatchString(yy, "baseline")) goto l125;  goto l124;
  l125:;	  yy->__pos= yypos124; yy->__thunkpos= yythunkpos124;  if (!yymatchString(yy, "enhanced")) goto l126;  goto l124;
  l126:;	  yy->__pos= yypos124; yy->__thunkpos= yythunkpos124;  if (!yy_MiscUntilEOL(yy)) goto l123;  yyDo(yy, yy_1_Mode, yy->__begin, yy->__end);
  }
  l124:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "Mode", yy->__buf+yy->__pos));
  return 1;
  l123:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Mode", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_ClosingBracket(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "ClosingBracket"));  if (!yymatchChar(yy, ')')) goto l127;
  yyprintf((stderr, "  ok   %s @ %s\n", "ClosingBracket", yy->__buf+yy->__pos));
  return 1;
  l127:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "ClosingBracket", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_OpenBracket(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "OpenBracket"));  if (!yymatchChar(yy, '(')) goto l128;
  yyprintf((stderr, "  ok   %s @ %s\n", "OpenBracket", yy->__buf+yy->__pos));
  return 1;
  l128:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "OpenBracket", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_MiscUntilEOL(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "MiscUntilEOL"));  if (!yymatchClass(yy, (unsigned char *)"\377\333\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377")) goto l129;
  l130:;	
  {  int yypos131= yy->__pos, yythunkpos131= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\377\333\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377")) goto l131;  goto l130;
  l131:;	  yy->__pos= yypos131; yy->__thunkpos= yythunkpos131;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "MiscUntilEOL", yy->__buf+yy->__pos));
  return 1;
  l129:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "MiscUntilEOL", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_TagLine(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "TagLine"));
  {  int yypos133= yy->__pos, yythunkpos133= yy->__thunkpos;  if (!yy_Tag(yy)) goto l134;  if (!yy_Semicolon(yy)) goto l134;  if (!yy_Requirements(yy)) goto l134;  if (!yy_Semicolon(yy)) goto l134;  if (!yy_Content(yy)) goto l134;  yyDo(yy, yy_1_TagLine, yy->__begin, yy->__end);  goto l133;
  l134:;	  yy->__pos= yypos133; yy->__thunkpos= yythunkpos133;  if (!yy_Tag(yy)) goto l135;  if (!yy_Semicolon(yy)) goto l135;  if (!yy_Requirements(yy)) goto l135;  if (!yy_Semicolon(yy)) goto l135;  yyDo(yy, yy_2_TagLine, yy->__begin, yy->__end);  goto l133;
  l135:;	  yy->__pos= yypos133; yy->__thunkpos= yythunkpos133;  if (!yy_Tag(yy)) goto l136;  if (!yy_Semicolon(yy)) goto l136;  if (!yy_Requirements(yy)) goto l136;  yyDo(yy, yy_3_TagLine, yy->__begin, yy->__end);  goto l133;
  l136:;	  yy->__pos= yypos133; yy->__thunkpos= yythunkpos133;  if (!yy_Tag(yy)) goto l137;  if (!yy_Semicolon(yy)) goto l137;  yyDo(yy, yy_4_TagLine, yy->__begin, yy->__end);  goto l133;
  l137:;	  yy->__pos= yypos133; yy->__thunkpos= yythunkpos133;  if (!yy_Tag(yy)) goto l132;  yyDo(yy, yy_5_TagLine, yy->__begin, yy->__end);
  }
  l133:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "TagLine", yy->__buf+yy->__pos));
  return 1;
  l132:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "TagLine", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_IncludeLine(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "IncludeLine"));  if (!yymatchString(yy, "include")) goto l138;  if (!yy_OpenBracket(yy)) goto l138;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l138;
#undef yytext
#undef yyleng
  }  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\340\377\003\376\377\377\207\376\377\377\007\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l138;
  l139:;	
  {  int yypos140= yy->__pos, yythunkpos140= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\340\377\003\376\377\377\207\376\377\377\007\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l140;  goto l139;
  l140:;	  yy->__pos= yypos140; yy->__thunkpos= yythunkpos140;
  }  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l138;
#undef yytext
#undef yyleng
  }  if (!yy_ClosingBracket(yy)) goto l138;  yyDo(yy, yy_1_IncludeLine, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "IncludeLine", yy->__buf+yy->__pos));
  return 1;
  l138:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "IncludeLine", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_ModeLine(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "ModeLine"));
  {  int yypos142= yy->__pos, yythunkpos142= yy->__thunkpos;  if (!yymatchString(yy, "mode")) goto l143;  if (!yy_OpenBracket(yy)) goto l143;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l143;
#undef yytext
#undef yyleng
  }  if (!yy_Mode(yy)) goto l143;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l143;
#undef yytext
#undef yyleng
  }  if (!yy_ClosingBracket(yy)) goto l143;  yyDo(yy, yy_1_ModeLine, yy->__begin, yy->__end);  goto l142;
  l143:;	  yy->__pos= yypos142; yy->__thunkpos= yythunkpos142;  if (!yymatchString(yy, "mode")) goto l144;  if (!yy_OpenBracket(yy)) goto l144;  if (!yy_Mode(yy)) goto l144;  yyDo(yy, yy_2_ModeLine, yy->__begin, yy->__end);  goto l142;
  l144:;	  yy->__pos= yypos142; yy->__thunkpos= yythunkpos142;  if (!yymatchString(yy, "mode")) goto l145;  if (!yy_OpenBracket(yy)) goto l145;  yyDo(yy, yy_3_ModeLine, yy->__begin, yy->__end);  goto l142;
  l145:;	  yy->__pos= yypos142; yy->__thunkpos= yythunkpos142;  if (!yymatchString(yy, "mode")) goto l141;  yyDo(yy, yy_4_ModeLine, yy->__begin, yy->__end);
  }
  l142:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "ModeLine", yy->__buf+yy->__pos));
  return 1;
  l141:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "ModeLine", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_SpaceLine(yycontext *yy)
{
  yyprintf((stderr, "%s\n", "SpaceLine"));
  l147:;	
  {  int yypos148= yy->__pos, yythunkpos148= yy->__thunkpos;  if (!yy_Space(yy)) goto l148;  goto l147;
  l148:;	  yy->__pos= yypos148; yy->__thunkpos= yythunkpos148;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "SpaceLine", yy->__buf+yy->__pos));
  return 1;
}
YY_RULE(int) yy_EndOfLine(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "EndOfLine"));  if (!yymatchClass(yy, (unsigned char *)"\000\044\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l149;  yyDo(yy, yy_1_EndOfLine, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "EndOfLine", yy->__buf+yy->__pos));
  return 1;
  l149:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "EndOfLine", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_CommentLine(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "CommentLine"));  if (!yymatchChar(yy, '#')) goto l150;
  l151:;	
  {  int yypos152= yy->__pos, yythunkpos152= yy->__thunkpos;
  {  int yypos153= yy->__pos, yythunkpos153= yy->__thunkpos;  if (!yy_EndOfLine(yy)) goto l153;  goto l152;
  l153:;	  yy->__pos= yypos153; yy->__thunkpos= yythunkpos153;
  }  if (!yymatchDot(yy)) goto l152;  goto l151;
  l152:;	  yy->__pos= yypos152; yy->__thunkpos= yythunkpos152;
  }  yyDo(yy, yy_1_CommentLine, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "CommentLine", yy->__buf+yy->__pos));
  return 1;
  l150:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "CommentLine", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_EndOfFile(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "EndOfFile"));
  {  int yypos155= yy->__pos, yythunkpos155= yy->__thunkpos;  if (!yymatchDot(yy)) goto l155;  goto l154;
  l155:;	  yy->__pos= yypos155; yy->__thunkpos= yythunkpos155;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "EndOfFile", yy->__buf+yy->__pos));
  return 1;
  l154:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "EndOfFile", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_Line(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "Line"));
  {  int yypos157= yy->__pos, yythunkpos157= yy->__thunkpos;  if (!yy_CommentLine(yy)) goto l158;  if (!yy_EndOfLine(yy)) goto l158;  goto l157;
  l158:;	  yy->__pos= yypos157; yy->__thunkpos= yythunkpos157;  if (!yy_SpaceLine(yy)) goto l159;  if (!yy_EndOfLine(yy)) goto l159;  goto l157;
  l159:;	  yy->__pos= yypos157; yy->__thunkpos= yythunkpos157;  if (!yy_ModeLine(yy)) goto l160;  if (!yy_EndOfLine(yy)) goto l160;  goto l157;
  l160:;	  yy->__pos= yypos157; yy->__thunkpos= yythunkpos157;  if (!yy_IncludeLine(yy)) goto l161;  if (!yy_EndOfLine(yy)) goto l161;  goto l157;
  l161:;	  yy->__pos= yypos157; yy->__thunkpos= yythunkpos157;  if (!yy_TagLine(yy)) goto l162;  if (!yy_EndOfLine(yy)) goto l162;  goto l157;
  l162:;	  yy->__pos= yypos157; yy->__thunkpos= yythunkpos157;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l156;
#undef yytext
#undef yyleng
  }  if (!yy_MiscUntilEOL(yy)) goto l156;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l156;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_1_Line, yy->__begin, yy->__end);
  }
  l157:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "Line", yy->__buf+yy->__pos));
  return 1;
  l156:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Line", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_start(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "start"));  if (!yy_Line(yy)) goto l163;
  l164:;	
  {  int yypos165= yy->__pos, yythunkpos165= yy->__thunkpos;  if (!yy_Line(yy)) goto l165;  goto l164;
  l165:;	  yy->__pos= yypos165; yy->__thunkpos= yythunkpos165;
  }  if (!yy_EndOfFile(yy)) goto l163;
  yyprintf((stderr, "  ok   %s @ %s\n", "start", yy->__buf+yy->__pos));
  return 1;
  l163:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "start", yy->__buf+yy->__pos));
  return 0;
}

#ifndef YY_PART

typedef int (*yyrule)(yycontext *yy);

YY_PARSE(int) YYPARSEFROM(YY_CTX_PARAM_ yyrule yystart)
{
  int yyok;
  if (!yyctx->__buflen)
    {
      yyctx->__buflen= YY_BUFFER_SIZE;
      yyctx->__buf= (char *)YY_MALLOC(yyctx, yyctx->__buflen);
      yyctx->__textlen= YY_BUFFER_SIZE;
      yyctx->__text= (char *)YY_MALLOC(yyctx, yyctx->__textlen);
      yyctx->__thunkslen= YY_STACK_SIZE;
      yyctx->__thunks= (yythunk *)YY_MALLOC(yyctx, sizeof(yythunk) * yyctx->__thunkslen);
      yyctx->__valslen= YY_STACK_SIZE;
      yyctx->__vals= (YYSTYPE *)YY_MALLOC(yyctx, sizeof(YYSTYPE) * yyctx->__valslen);
      yyctx->__begin= yyctx->__end= yyctx->__pos= yyctx->__limit= yyctx->__thunkpos= 0;
    }
  yyctx->__begin= yyctx->__end= yyctx->__pos;
  yyctx->__thunkpos= 0;
  yyctx->__val= yyctx->__vals;
  yyok= yystart(yyctx);
  if (yyok) yyDone(yyctx);
  yyCommit(yyctx);
  return yyok;
}

YY_PARSE(int) YYPARSE(YY_CTX_PARAM)
{
  return YYPARSEFROM(YY_CTX_ARG_ yy_start);
}

YY_PARSE(yycontext *) YYRELEASE(yycontext *yyctx)
{
  if (yyctx->__buflen)
    {
      yyctx->__buflen= 0;
      YY_FREE(yyctx, yyctx->__buf);
      YY_FREE(yyctx, yyctx->__text);
      YY_FREE(yyctx, yyctx->__thunks);
      YY_FREE(yyctx, yyctx->__vals);
    }
  return yyctx;
}

#endif
