/* A recursive-descent parser generated by peg 0.1.18 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#define YYRULECOUNT 41
#ifndef YY_MALLOC
#define YY_MALLOC(C, N)		malloc(N)
#endif
#ifndef YY_REALLOC
#define YY_REALLOC(C, P, N)	realloc(P, N)
#endif
#ifndef YY_FREE
#define YY_FREE(C, P)		free(P)
#endif
#ifndef YY_LOCAL
#define YY_LOCAL(T)	static T
#endif
#ifndef YY_ACTION
#define YY_ACTION(T)	static T
#endif
#ifndef YY_RULE
#define YY_RULE(T)	static T
#endif
#ifndef YY_PARSE
#define YY_PARSE(T)	T
#endif
#ifndef YYPARSE
#define YYPARSE		yyparse
#endif
#ifndef YYPARSEFROM
#define YYPARSEFROM	yyparsefrom
#endif
#ifndef YYRELEASE
#define YYRELEASE	yyrelease
#endif
#ifndef YY_BEGIN
#define YY_BEGIN	( yy->__begin= yy->__pos, 1)
#endif
#ifndef YY_END
#define YY_END		( yy->__end= yy->__pos, 1)
#endif
#ifdef YY_DEBUG
# define yyprintf(args)	fprintf args
#else
# define yyprintf(args)
#endif
#ifndef YYSTYPE
#define YYSTYPE	int
#endif
#ifndef YY_STACK_SIZE
#define YY_STACK_SIZE 128
#endif

#ifndef YY_BUFFER_SIZE
#define YY_BUFFER_SIZE 1024
#endif

#ifndef YY_PART

typedef struct _yycontext yycontext;
typedef void (*yyaction)(yycontext *yy, char *yytext, int yyleng);
typedef struct _yythunk { int begin, end;  yyaction  action;  struct _yythunk *next; } yythunk;

struct _yycontext {
  char     *__buf;
  int       __buflen;
  int       __pos;
  int       __limit;
  char     *__text;
  int       __textlen;
  int       __begin;
  int       __end;
  int       __textmax;
  yythunk  *__thunks;
  int       __thunkslen;
  int       __thunkpos;
  YYSTYPE   __;
  YYSTYPE  *__val;
  YYSTYPE  *__vals;
  int       __valslen;
#ifdef YY_CTX_MEMBERS
  YY_CTX_MEMBERS
#endif
};

#ifdef YY_CTX_LOCAL
#define YY_CTX_PARAM_	yycontext *yyctx,
#define YY_CTX_PARAM	yycontext *yyctx
#define YY_CTX_ARG_	yyctx,
#define YY_CTX_ARG	yyctx
#ifndef YY_INPUT
#define YY_INPUT(yy, buf, result, max_size)		\
  {							\
    int yyc= getchar();					\
    result= (EOF == yyc) ? 0 : (*(buf)= yyc, 1);	\
    yyprintf((stderr, "<%c>", yyc));			\
  }
#endif
#else
#define YY_CTX_PARAM_
#define YY_CTX_PARAM
#define YY_CTX_ARG_
#define YY_CTX_ARG
yycontext _yyctx= { 0, 0 };
yycontext *yyctx= &_yyctx;
#ifndef YY_INPUT
#define YY_INPUT(buf, result, max_size)			\
  {							\
    int yyc= getchar();					\
    result= (EOF == yyc) ? 0 : (*(buf)= yyc, 1);	\
    yyprintf((stderr, "<%c>", yyc));			\
  }
#endif
#endif

YY_LOCAL(int) yyrefill(yycontext *yy)
{
  int yyn;
  while (yy->__buflen - yy->__pos < 512)
    {
      yy->__buflen *= 2;
      yy->__buf= (char *)YY_REALLOC(yy, yy->__buf, yy->__buflen);
    }
#ifdef YY_CTX_LOCAL
  YY_INPUT(yy, (yy->__buf + yy->__pos), yyn, (yy->__buflen - yy->__pos));
#else
  YY_INPUT((yy->__buf + yy->__pos), yyn, (yy->__buflen - yy->__pos));
#endif
  if (!yyn) return 0;
  yy->__limit += yyn;
  return 1;
}

YY_LOCAL(int) yymatchDot(yycontext *yy)
{
  if (yy->__pos >= yy->__limit && !yyrefill(yy)) return 0;
  ++yy->__pos;
  return 1;
}

YY_LOCAL(int) yymatchChar(yycontext *yy, int c)
{
  if (yy->__pos >= yy->__limit && !yyrefill(yy)) return 0;
  if ((unsigned char)yy->__buf[yy->__pos] == c)
    {
      ++yy->__pos;
      yyprintf((stderr, "  ok   yymatchChar(yy, %c) @ %s\n", c, yy->__buf+yy->__pos));
      return 1;
    }
  yyprintf((stderr, "  fail yymatchChar(yy, %c) @ %s\n", c, yy->__buf+yy->__pos));
  return 0;
}

YY_LOCAL(int) yymatchString(yycontext *yy, const char *s)
{
  int yysav= yy->__pos;
  while (*s)
    {
      if (yy->__pos >= yy->__limit && !yyrefill(yy)) return 0;
      if (yy->__buf[yy->__pos] != *s)
        {
          yy->__pos= yysav;
          return 0;
        }
      ++s;
      ++yy->__pos;
    }
  return 1;
}

YY_LOCAL(int) yymatchClass(yycontext *yy, unsigned char *bits)
{
  int c;
  if (yy->__pos >= yy->__limit && !yyrefill(yy)) return 0;
  c= (unsigned char)yy->__buf[yy->__pos];
  if (bits[c >> 3] & (1 << (c & 7)))
    {
      ++yy->__pos;
      yyprintf((stderr, "  ok   yymatchClass @ %s\n", yy->__buf+yy->__pos));
      return 1;
    }
  yyprintf((stderr, "  fail yymatchClass @ %s\n", yy->__buf+yy->__pos));
  return 0;
}

YY_LOCAL(void) yyDo(yycontext *yy, yyaction action, int begin, int end)
{
  while (yy->__thunkpos >= yy->__thunkslen)
    {
      yy->__thunkslen *= 2;
      yy->__thunks= (yythunk *)YY_REALLOC(yy, yy->__thunks, sizeof(yythunk) * yy->__thunkslen);
    }
  yy->__thunks[yy->__thunkpos].begin=  begin;
  yy->__thunks[yy->__thunkpos].end=    end;
  yy->__thunks[yy->__thunkpos].action= action;
  ++yy->__thunkpos;
}

YY_LOCAL(int) yyText(yycontext *yy, int begin, int end)
{
  int yyleng= end - begin;
  if (yyleng <= 0)
    yyleng= 0;
  else
    {
      while (yy->__textlen < (yyleng + 1))
	{
	  yy->__textlen *= 2;
	  yy->__text= (char *)YY_REALLOC(yy, yy->__text, yy->__textlen);
	}
      memcpy(yy->__text, yy->__buf + begin, yyleng);
    }
  yy->__text[yyleng]= '\0';
  return yyleng;
}

YY_LOCAL(void) yyDone(yycontext *yy)
{
  int pos;
  for (pos= 0;  pos < yy->__thunkpos;  ++pos)
    {
      yythunk *thunk= &yy->__thunks[pos];
      int yyleng= thunk->end ? yyText(yy, thunk->begin, thunk->end) : thunk->begin;
      yyprintf((stderr, "DO [%d] %p %s\n", pos, thunk->action, yy->__text));
      thunk->action(yy, yy->__text, yyleng);
    }
  yy->__thunkpos= 0;
}

YY_LOCAL(void) yyCommit(yycontext *yy)
{
  if ((yy->__limit -= yy->__pos))
    {
      memmove(yy->__buf, yy->__buf + yy->__pos, yy->__limit);
    }
  yy->__begin -= yy->__pos;
  yy->__end -= yy->__pos;
  yy->__pos= yy->__thunkpos= 0;
}

YY_LOCAL(int) yyAccept(yycontext *yy, int tp0)
{
  if (tp0)
    {
      fprintf(stderr, "accept denied at %d\n", tp0);
      return 0;
    }
  else
    {
      yyDone(yy);
      yyCommit(yy);
    }
  return 1;
}

YY_LOCAL(void) yyPush(yycontext *yy, char *text, int count)
{
  yy->__val += count;
  while (yy->__valslen <= yy->__val - yy->__vals)
    {
      long offset= yy->__val - yy->__vals;
      yy->__valslen *= 2;
      yy->__vals= (YYSTYPE *)YY_REALLOC(yy, yy->__vals, sizeof(YYSTYPE) * yy->__valslen);
      yy->__val= yy->__vals + offset;
    }
}
YY_LOCAL(void) yyPop(yycontext *yy, char *text, int count)   { yy->__val -= count; }
YY_LOCAL(void) yySet(yycontext *yy, char *text, int count)   { yy->__val[count]= yy->__; }

#endif /* YY_PART */

#define	YYACCEPT	yyAccept(yy, yythunkpos0)

YY_RULE(int) yy_EscapedPCRE(yycontext *yy); /* 41 */
YY_RULE(int) yy_PCRE(yycontext *yy); /* 40 */
YY_RULE(int) yy_Value(yycontext *yy); /* 39 */
YY_RULE(int) yy_ValueList(yycontext *yy); /* 38 */
YY_RULE(int) yy_Digit(yycontext *yy); /* 37 */
YY_RULE(int) yy_Iccprofile(yycontext *yy); /* 36 */
YY_RULE(int) yy_Datetime(yycontext *yy); /* 35 */
YY_RULE(int) yy_ValueReference(yycontext *yy); /* 34 */
YY_RULE(int) yy_Dot(yycontext *yy); /* 33 */
YY_RULE(int) yy_OptDepends(yycontext *yy); /* 32 */
YY_RULE(int) yy_IfDepends(yycontext *yy); /* 31 */
YY_RULE(int) yy_Space(yycontext *yy); /* 30 */
YY_RULE(int) yy_TagReference(yycontext *yy); /* 29 */
YY_RULE(int) yy_Content(yycontext *yy); /* 28 */
YY_RULE(int) yy_Requirements(yycontext *yy); /* 27 */
YY_RULE(int) yy_Semicolon(yycontext *yy); /* 26 */
YY_RULE(int) yy_Tag(yycontext *yy); /* 25 */
YY_RULE(int) yy_Colon(yycontext *yy); /* 24 */
YY_RULE(int) yy_PrintableAscii(yycontext *yy); /* 23 */
YY_RULE(int) yy_RegEx(yycontext *yy); /* 22 */
YY_RULE(int) yy_NTupel(yycontext *yy); /* 21 */
YY_RULE(int) yy_Number(yycontext *yy); /* 20 */
YY_RULE(int) yy_Only(yycontext *yy); /* 19 */
YY_RULE(int) yy_Range(yycontext *yy); /* 18 */
YY_RULE(int) yy_Any(yycontext *yy); /* 17 */
YY_RULE(int) yy_LogicalOrListElement(yycontext *yy); /* 16 */
YY_RULE(int) yy_LogicalOrList(yycontext *yy); /* 15 */
YY_RULE(int) yy_LogicalOr(yycontext *yy); /* 14 */
YY_RULE(int) yy_Mode(yycontext *yy); /* 13 */
YY_RULE(int) yy_ClosingBracket(yycontext *yy); /* 12 */
YY_RULE(int) yy_OpenBracket(yycontext *yy); /* 11 */
YY_RULE(int) yy_MiscUntilEOL(yycontext *yy); /* 10 */
YY_RULE(int) yy_TagLine(yycontext *yy); /* 9 */
YY_RULE(int) yy_IncludeLine(yycontext *yy); /* 8 */
YY_RULE(int) yy_ModeLine(yycontext *yy); /* 7 */
YY_RULE(int) yy_SpaceLine(yycontext *yy); /* 6 */
YY_RULE(int) yy_EndOfLine(yycontext *yy); /* 5 */
YY_RULE(int) yy_CommentLine(yycontext *yy); /* 4 */
YY_RULE(int) yy_EndOfFile(yycontext *yy); /* 3 */
YY_RULE(int) yy_Line(yycontext *yy); /* 2 */
YY_RULE(int) yy_start(yycontext *yy); /* 1 */

YY_ACTION(void) yy_1_EndOfLine(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_EndOfLine\n"));
  {
#line 0
  incrlineno(); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_6_RegEx(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_6_RegEx\n"));
  {
#line 0
   set_parse_error("'regex' expects an open bracket", yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_5_RegEx(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_5_RegEx\n"));
  {
#line 0
   set_parse_error("'regex' expects an open '\"'", yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_4_RegEx(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_4_RegEx\n"));
  {
#line 0
   set_parse_error("'regex' expects a PCRE-regex", yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_3_RegEx(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_3_RegEx\n"));
  {
#line 0
   set_parse_error("'regex' expects a closing '\"'", yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_2_RegEx(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_RegEx\n"));
  {
#line 0
   set_parse_error("'regex' expects a closing bracket", yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_RegEx(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_RegEx\n"));
  {
#line 0
   regex_push ( yytext ); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_4_Only(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_4_Only\n"));
  {
#line 0
   set_parse_error("'only' expects an open bracket", yytext);;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_3_Only(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_3_Only\n"));
  {
#line 0
   set_parse_error("'only' expects a value list", yytext);;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_2_Only(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_Only\n"));
  {
#line 0
   set_parse_error("'only' expects a closing bracket", yytext);;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_Only(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_Only\n"));
  {
#line 0
    ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_7_ValueReference(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_7_ValueReference\n"));
  {
#line 0
   set_parse_error("value reference error: '%s'", yytext);;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_6_ValueReference(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_6_ValueReference\n"));
  {
#line 0
   parser_state.any_reference = only_ref; ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_5_ValueReference(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_5_ValueReference\n"));
  {
#line 0
   parser_state.any_reference = ntupel_ref; ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_4_ValueReference(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_4_ValueReference\n"));
  {
#line 0
   parser_state.any_reference = range_ref; ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_3_ValueReference(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_3_ValueReference\n"));
  {
#line 0
   parser_state.any_reference = regex_ref; ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_2_ValueReference(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_ValueReference\n"));
  {
#line 0
   parser_state.any_reference = only_ref; i_push(atol(yytext) );;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_ValueReference(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_ValueReference\n"));
  {
#line 0
   parser_state.any_reference = any_ref; ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_4_NTupel(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_4_NTupel\n"));
  {
#line 0
   set_parse_error("'ntupel' expects an open bracket", yytext);;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_3_NTupel(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_3_NTupel\n"));
  {
#line 0
   set_parse_error("'ntupel' expects a value list", yytext);;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_2_NTupel(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_NTupel\n"));
  {
#line 0
   set_parse_error("'ntupel' expects a closing bracket", yytext);;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_NTupel(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_NTupel\n"));
  {
#line 0
  int v=parser_state.valuelist; i_push(v); reset_valuelist(); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_Value(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_Value\n"));
  {
#line 0
   incr_values(); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_Dot(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_Dot\n"));
  {
#line 0
   set_parse_error("missed dot", yytext);
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_Colon(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_Colon\n"));
  {
#line 0
   set_parse_error("missed colon", yytext);;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_3_Number(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_3_Number\n"));
  {
#line 0
   i_push(atol(yytext) );;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_2_Number(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_Number\n"));
  {
#line 0
   i_push(2<<atol(yytext) ); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_Number(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_Number\n"));
  {
#line 0
   i_push(strtol(yytext, NULL, 0) ); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_5_Range(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_5_Range\n"));
  {
#line 0
   set_parse_error("'range' expects an open bracket", yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_4_Range(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_4_Range\n"));
  {
#line 0
   set_parse_error("'range' expects a number", yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_3_Range(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_3_Range\n"));
  {
#line 0
   set_parse_error("'range' expects a colon", yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_2_Range(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_Range\n"));
  {
#line 0
   set_parse_error("'range' expects a number", yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_Range(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_Range\n"));
  {
#line 0
   set_parse_error("'range' expects a closing bracket", yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_9_Content(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_9_Content\n"));
  {
#line 0
   set_parse_error("wrong values-keyword", yytext);;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_8_Content(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_8_Content\n"));
  {
#line 0
   v_push( iccprofile ); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_7_Content(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_7_Content\n"));
  {
#line 0
   v_push( datetime ); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_6_Content(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_6_Content\n"));
  {
#line 0
   v_push( printable_ascii ); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_5_Content(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_5_Content\n"));
  {
#line 0
   v_push( regex ); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_4_Content(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_4_Content\n"));
  {
#line 0
   v_push( ntupel ); reset_valuelist() ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_3_Content(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_3_Content\n"));
  {
#line 0
   v_push( only ); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_2_Content(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_Content\n"));
  {
#line 0
   v_push( range); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_Content(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_Content\n"));
  {
#line 0
   v_push( any ); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_5_OptDepends(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_5_OptDepends\n"));
  {
#line 0
   set_parse_error("'optdepends' expects an open bracket",  yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_4_OptDepends(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_4_OptDepends\n"));
  {
#line 0
   set_parse_error("'optdepends' expects a tagreference",  yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_3_OptDepends(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_3_OptDepends\n"));
  {
#line 0
   set_parse_error("'optdepends' expects a dot",  yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_2_OptDepends(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_OptDepends\n"));
  {
#line 0
   set_parse_error("'optdepends' expects a value reference",  yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_OptDepends(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_OptDepends\n"));
  {
#line 0
   set_parse_error("'optdepends' expects a closing bracket",  yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_5_IfDepends(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_5_IfDepends\n"));
  {
#line 0
   set_parse_error("'depends' expects an open bracket",  yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_4_IfDepends(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_4_IfDepends\n"));
  {
#line 0
   set_parse_error("'depends' expects a tagreference",  yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_3_IfDepends(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_3_IfDepends\n"));
  {
#line 0
   set_parse_error("'depends' expects a dot",  yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_2_IfDepends(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_IfDepends\n"));
  {
#line 0
   set_parse_error("'depends' expects a value reference",  yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_IfDepends(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_IfDepends\n"));
  {
#line 0
   set_parse_error("'depends' expects a closing bracket",  yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_5_Requirements(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_5_Requirements\n"));
  {
#line 0
   set_parse_error("wrong requirements-keyword", yytext);;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_4_Requirements(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_4_Requirements\n"));
  {
#line 0
   set_optional(); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_3_Requirements(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_3_Requirements\n"));
  {
#line 0
   set_optdepends(); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_2_Requirements(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_Requirements\n"));
  {
#line 0
   set_ifdepends(); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_Requirements(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_Requirements\n"));
  {
#line 0
   set_mandatory(); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_Semicolon(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_Semicolon\n"));
  {
#line 0
   set_parse_error("missed semicolon", yytext);;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_2_TagReference(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_TagReference\n"));
  {
#line 0
   set_parse_error("wrong tagreference", yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_TagReference(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_TagReference\n"));
  {
#line 0
  
                        int tag = i_pop();
                        if (tag < 254) set_parse_error("wrong tagreference (should be >253)", yytext);
                        else if (tag > 65535) set_parse_error("wrong tagreference (should be <65536)", yytext);
                        else settagref( tag );
                ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_Tag(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_Tag\n"));
  {
#line 0
  
                        int tag = i_pop();
                        /* rule_tagorder_in_dsl( tag ); */
                        if (tag < 254) set_parse_error("wrong tag (should be >253)", yytext);
                        else if (tag > 65535) set_parse_error("wrong tag (should be <65536)", yytext);
                        else settag( tag );
                ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_5_TagLine(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_5_TagLine\n"));
  {
#line 0
   set_parse_error("tagline expects missed semicolon here", yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_4_TagLine(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_4_TagLine\n"));
  {
#line 0
   set_parse_error("tagline requires a requiemrent-keyword (mandatory, etc.)",yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_3_TagLine(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_3_TagLine\n"));
  {
#line 0
   set_parse_error("tagline expects missed semicolon here", yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_2_TagLine(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_TagLine\n"));
  {
#line 0
   set_parse_error("tagline requires content", yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_TagLine(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_TagLine\n"));
  {
#line 0
   rule_addtag_config();  ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_5_Mode(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_5_Mode\n"));
  {
#line 0
   set_parse_error("mode expects either 'baseline' or 'enhanced'", yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_4_Mode(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_4_Mode\n"));
  {
#line 0
   i_push(mode_enable_ifd_checks); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_3_Mode(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_3_Mode\n"));
  {
#line 0
   i_push(mode_enable_offset_checks); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_2_Mode(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_Mode\n"));
  {
#line 0
   i_push(mode_enable_type_checks); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_Mode(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_Mode\n"));
  {
#line 0
   i_push(mode_baseline ); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_8_LogicalOrListElement(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_8_LogicalOrListElement\n"));
  {
#line 0
   set_parse_error("wrong values-keyword", yytext);;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_7_LogicalOrListElement(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_7_LogicalOrListElement\n"));
  {
#line 0
   v_push( printable_ascii );incr_logical_elements();  ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_6_LogicalOrListElement(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_6_LogicalOrListElement\n"));
  {
#line 0
   v_push( regex );incr_logical_elements();  ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_5_LogicalOrListElement(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_5_LogicalOrListElement\n"));
  {
#line 0
   v_push( ntupel); reset_valuelist(); incr_logical_elements(); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_4_LogicalOrListElement(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_4_LogicalOrListElement\n"));
  {
#line 0
   v_push( only );incr_logical_elements();  ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_3_LogicalOrListElement(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_3_LogicalOrListElement\n"));
  {
#line 0
   v_push( only );incr_logical_elements();  ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_2_LogicalOrListElement(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_LogicalOrListElement\n"));
  {
#line 0
   v_push( range);incr_logical_elements();  ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_LogicalOrListElement(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_LogicalOrListElement\n"));
  {
#line 0
   v_push( any );incr_logical_elements(); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_LogicalOr(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_LogicalOr\n"));
  {
#line 0
   rule_add_logical_config(); reset_logical_list();;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_4_ModeLine(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_4_ModeLine\n"));
  {
#line 0
   set_parse_error( "modeline requires an open bracket", yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_3_ModeLine(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_3_ModeLine\n"));
  {
#line 0
   set_parse_error( "modeline requires a mode", yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_2_ModeLine(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_ModeLine\n"));
  {
#line 0
   set_parse_error( "modeline expects a closing bracket", yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_ModeLine(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_ModeLine\n"));
  {
#line 0
   int i = i_pop(); set_mode( i );  ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_IncludeLine(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_IncludeLine\n"));
  {
#line 0
   set_include ( yytext );  ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_CommentLine(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_CommentLine\n"));
  {
#line 0
   commentline(); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_Line(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_Line\n"));
  {
#line 0
   set_parse_error("wrong line entry",yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}

YY_RULE(int) yy_EscapedPCRE(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "EscapedPCRE"));
  {  int yypos2= yy->__pos, yythunkpos2= yy->__thunkpos;  if (!yymatchChar(yy, '\\')) goto l3;  if (!yymatchChar(yy, '\\')) goto l3;  goto l2;
  l3:;	  yy->__pos= yypos2; yy->__thunkpos= yythunkpos2;  if (!yymatchChar(yy, '\\')) goto l1;  if (!yymatchChar(yy, '"')) goto l1;
  }
  l2:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "EscapedPCRE", yy->__buf+yy->__pos));
  return 1;
  l1:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "EscapedPCRE", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_PCRE(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "PCRE"));
  {  int yypos5= yy->__pos, yythunkpos5= yy->__thunkpos;  if (!yy_EscapedPCRE(yy)) goto l6;  goto l5;
  l6:;	  yy->__pos= yypos5; yy->__thunkpos= yythunkpos5;  if (!yymatchClass(yy, (unsigned char *)"\377\377\377\377\373\377\377\377\377\377\377\357\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377")) goto l4;
  }
  l5:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "PCRE", yy->__buf+yy->__pos));
  return 1;
  l4:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "PCRE", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_Value(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "Value"));  if (!yy_Number(yy)) goto l7;  yyDo(yy, yy_1_Value, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "Value", yy->__buf+yy->__pos));
  return 1;
  l7:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Value", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_ValueList(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "ValueList"));  if (!yy_Value(yy)) goto l8;
  l9:;	
  {  int yypos10= yy->__pos, yythunkpos10= yy->__thunkpos;  if (!yy_Colon(yy)) goto l10;  if (!yy_Value(yy)) goto l10;  goto l9;
  l10:;	  yy->__pos= yypos10; yy->__thunkpos= yythunkpos10;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "ValueList", yy->__buf+yy->__pos));
  return 1;
  l8:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "ValueList", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_Digit(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "Digit"));  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l11;
  yyprintf((stderr, "  ok   %s @ %s\n", "Digit", yy->__buf+yy->__pos));
  return 1;
  l11:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Digit", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_Iccprofile(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "Iccprofile"));  if (!yymatchString(yy, "iccprofile")) goto l12;
  yyprintf((stderr, "  ok   %s @ %s\n", "Iccprofile", yy->__buf+yy->__pos));
  return 1;
  l12:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Iccprofile", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_Datetime(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "Datetime"));  if (!yymatchString(yy, "datetime")) goto l13;
  yyprintf((stderr, "  ok   %s @ %s\n", "Datetime", yy->__buf+yy->__pos));
  return 1;
  l13:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Datetime", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_ValueReference(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "ValueReference"));
  {  int yypos15= yy->__pos, yythunkpos15= yy->__thunkpos;  if (!yy_Any(yy)) goto l16;  yyDo(yy, yy_1_ValueReference, yy->__begin, yy->__end);  goto l15;
  l16:;	  yy->__pos= yypos15; yy->__thunkpos= yythunkpos15;  if (!yy_Number(yy)) goto l17;  yyDo(yy, yy_2_ValueReference, yy->__begin, yy->__end);  goto l15;
  l17:;	  yy->__pos= yypos15; yy->__thunkpos= yythunkpos15;  if (!yy_RegEx(yy)) goto l18;  yyDo(yy, yy_3_ValueReference, yy->__begin, yy->__end);  goto l15;
  l18:;	  yy->__pos= yypos15; yy->__thunkpos= yythunkpos15;  if (!yy_Range(yy)) goto l19;  yyDo(yy, yy_4_ValueReference, yy->__begin, yy->__end);  goto l15;
  l19:;	  yy->__pos= yypos15; yy->__thunkpos= yythunkpos15;  if (!yy_NTupel(yy)) goto l20;  yyDo(yy, yy_5_ValueReference, yy->__begin, yy->__end);  goto l15;
  l20:;	  yy->__pos= yypos15; yy->__thunkpos= yythunkpos15;  if (!yy_Only(yy)) goto l21;  yyDo(yy, yy_6_ValueReference, yy->__begin, yy->__end);  goto l15;
  l21:;	  yy->__pos= yypos15; yy->__thunkpos= yythunkpos15;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l14;
#undef yytext
#undef yyleng
  }  if (!yy_MiscUntilEOL(yy)) goto l14;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l14;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_7_ValueReference, yy->__begin, yy->__end);
  }
  l15:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "ValueReference", yy->__buf+yy->__pos));
  return 1;
  l14:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "ValueReference", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_Dot(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "Dot"));
  {  int yypos23= yy->__pos, yythunkpos23= yy->__thunkpos;  if (!yymatchChar(yy, '.')) goto l24;
  l25:;	
  {  int yypos26= yy->__pos, yythunkpos26= yy->__thunkpos;  if (!yy_Space(yy)) goto l26;  goto l25;
  l26:;	  yy->__pos= yypos26; yy->__thunkpos= yythunkpos26;
  }  goto l23;
  l24:;	  yy->__pos= yypos23; yy->__thunkpos= yythunkpos23;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l22;
#undef yytext
#undef yyleng
  }  if (!yy_MiscUntilEOL(yy)) goto l22;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l22;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_1_Dot, yy->__begin, yy->__end);
  }
  l23:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "Dot", yy->__buf+yy->__pos));
  return 1;
  l22:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Dot", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_OptDepends(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "OptDepends"));
  {  int yypos28= yy->__pos, yythunkpos28= yy->__thunkpos;  if (!yymatchString(yy, "optdepends")) goto l29;  if (!yy_OpenBracket(yy)) goto l29;  if (!yy_TagReference(yy)) goto l29;  if (!yy_Dot(yy)) goto l29;  if (!yy_ValueReference(yy)) goto l29;  if (!yy_ClosingBracket(yy)) goto l29;  goto l28;
  l29:;	  yy->__pos= yypos28; yy->__thunkpos= yythunkpos28;  if (!yymatchString(yy, "optdepends")) goto l30;  if (!yy_OpenBracket(yy)) goto l30;  if (!yy_TagReference(yy)) goto l30;  if (!yy_Dot(yy)) goto l30;  if (!yy_ValueReference(yy)) goto l30;  yyDo(yy, yy_1_OptDepends, yy->__begin, yy->__end);  goto l28;
  l30:;	  yy->__pos= yypos28; yy->__thunkpos= yythunkpos28;  if (!yymatchString(yy, "optdepends")) goto l31;  if (!yy_OpenBracket(yy)) goto l31;  if (!yy_TagReference(yy)) goto l31;  if (!yy_Dot(yy)) goto l31;  yyDo(yy, yy_2_OptDepends, yy->__begin, yy->__end);  goto l28;
  l31:;	  yy->__pos= yypos28; yy->__thunkpos= yythunkpos28;  if (!yymatchString(yy, "optdepends")) goto l32;  if (!yy_OpenBracket(yy)) goto l32;  if (!yy_TagReference(yy)) goto l32;  yyDo(yy, yy_3_OptDepends, yy->__begin, yy->__end);  goto l28;
  l32:;	  yy->__pos= yypos28; yy->__thunkpos= yythunkpos28;  if (!yymatchString(yy, "optdepends")) goto l33;  if (!yy_OpenBracket(yy)) goto l33;  yyDo(yy, yy_4_OptDepends, yy->__begin, yy->__end);  goto l28;
  l33:;	  yy->__pos= yypos28; yy->__thunkpos= yythunkpos28;  if (!yymatchString(yy, "optdepends")) goto l27;  yyDo(yy, yy_5_OptDepends, yy->__begin, yy->__end);
  }
  l28:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "OptDepends", yy->__buf+yy->__pos));
  return 1;
  l27:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "OptDepends", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_IfDepends(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "IfDepends"));
  {  int yypos35= yy->__pos, yythunkpos35= yy->__thunkpos;  if (!yymatchString(yy, "depends")) goto l36;  if (!yy_OpenBracket(yy)) goto l36;  if (!yy_TagReference(yy)) goto l36;  if (!yy_Dot(yy)) goto l36;  if (!yy_ValueReference(yy)) goto l36;  if (!yy_ClosingBracket(yy)) goto l36;  goto l35;
  l36:;	  yy->__pos= yypos35; yy->__thunkpos= yythunkpos35;  if (!yymatchString(yy, "depends")) goto l37;  if (!yy_OpenBracket(yy)) goto l37;  if (!yy_TagReference(yy)) goto l37;  if (!yy_Dot(yy)) goto l37;  if (!yy_ValueReference(yy)) goto l37;  yyDo(yy, yy_1_IfDepends, yy->__begin, yy->__end);  goto l35;
  l37:;	  yy->__pos= yypos35; yy->__thunkpos= yythunkpos35;  if (!yymatchString(yy, "depends")) goto l38;  if (!yy_OpenBracket(yy)) goto l38;  if (!yy_TagReference(yy)) goto l38;  if (!yy_Dot(yy)) goto l38;  yyDo(yy, yy_2_IfDepends, yy->__begin, yy->__end);  goto l35;
  l38:;	  yy->__pos= yypos35; yy->__thunkpos= yythunkpos35;  if (!yymatchString(yy, "depends")) goto l39;  if (!yy_OpenBracket(yy)) goto l39;  if (!yy_TagReference(yy)) goto l39;  yyDo(yy, yy_3_IfDepends, yy->__begin, yy->__end);  goto l35;
  l39:;	  yy->__pos= yypos35; yy->__thunkpos= yythunkpos35;  if (!yymatchString(yy, "depends")) goto l40;  if (!yy_OpenBracket(yy)) goto l40;  yyDo(yy, yy_4_IfDepends, yy->__begin, yy->__end);  goto l35;
  l40:;	  yy->__pos= yypos35; yy->__thunkpos= yythunkpos35;  if (!yymatchString(yy, "depends")) goto l34;  yyDo(yy, yy_5_IfDepends, yy->__begin, yy->__end);
  }
  l35:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "IfDepends", yy->__buf+yy->__pos));
  return 1;
  l34:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "IfDepends", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_Space(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "Space"));
  {  int yypos42= yy->__pos, yythunkpos42= yy->__thunkpos;  if (!yymatchChar(yy, ' ')) goto l43;  goto l42;
  l43:;	  yy->__pos= yypos42; yy->__thunkpos= yythunkpos42;  if (!yymatchChar(yy, '\t')) goto l41;
  }
  l42:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "Space", yy->__buf+yy->__pos));
  return 1;
  l41:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Space", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_TagReference(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "TagReference"));
  {  int yypos45= yy->__pos, yythunkpos45= yy->__thunkpos;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l46;
#undef yytext
#undef yyleng
  }  if (!yy_Number(yy)) goto l46;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l46;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_1_TagReference, yy->__begin, yy->__end);  goto l45;
  l46:;	  yy->__pos= yypos45; yy->__thunkpos= yythunkpos45;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l44;
#undef yytext
#undef yyleng
  }  if (!yy_MiscUntilEOL(yy)) goto l44;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l44;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_2_TagReference, yy->__begin, yy->__end);
  }
  l45:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "TagReference", yy->__buf+yy->__pos));
  return 1;
  l44:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "TagReference", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_Content(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "Content"));
  {  int yypos48= yy->__pos, yythunkpos48= yy->__thunkpos;  if (!yy_Any(yy)) goto l49;  yyDo(yy, yy_1_Content, yy->__begin, yy->__end);  goto l48;
  l49:;	  yy->__pos= yypos48; yy->__thunkpos= yythunkpos48;  if (!yy_Range(yy)) goto l50;  yyDo(yy, yy_2_Content, yy->__begin, yy->__end);  goto l48;
  l50:;	  yy->__pos= yypos48; yy->__thunkpos= yythunkpos48;  if (!yy_LogicalOr(yy)) goto l51;  goto l48;
  l51:;	  yy->__pos= yypos48; yy->__thunkpos= yythunkpos48;  if (!yy_Only(yy)) goto l52;  yyDo(yy, yy_3_Content, yy->__begin, yy->__end);  goto l48;
  l52:;	  yy->__pos= yypos48; yy->__thunkpos= yythunkpos48;  if (!yy_NTupel(yy)) goto l53;  yyDo(yy, yy_4_Content, yy->__begin, yy->__end);  goto l48;
  l53:;	  yy->__pos= yypos48; yy->__thunkpos= yythunkpos48;  if (!yy_RegEx(yy)) goto l54;  yyDo(yy, yy_5_Content, yy->__begin, yy->__end);  goto l48;
  l54:;	  yy->__pos= yypos48; yy->__thunkpos= yythunkpos48;  if (!yy_PrintableAscii(yy)) goto l55;  yyDo(yy, yy_6_Content, yy->__begin, yy->__end);  goto l48;
  l55:;	  yy->__pos= yypos48; yy->__thunkpos= yythunkpos48;  if (!yy_Datetime(yy)) goto l56;  yyDo(yy, yy_7_Content, yy->__begin, yy->__end);  goto l48;
  l56:;	  yy->__pos= yypos48; yy->__thunkpos= yythunkpos48;  if (!yy_Iccprofile(yy)) goto l57;  yyDo(yy, yy_8_Content, yy->__begin, yy->__end);  goto l48;
  l57:;	  yy->__pos= yypos48; yy->__thunkpos= yythunkpos48;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l47;
#undef yytext
#undef yyleng
  }  if (!yy_MiscUntilEOL(yy)) goto l47;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l47;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_9_Content, yy->__begin, yy->__end);
  }
  l48:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "Content", yy->__buf+yy->__pos));
  return 1;
  l47:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Content", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_Requirements(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "Requirements"));
  {  int yypos59= yy->__pos, yythunkpos59= yy->__thunkpos;  if (!yymatchString(yy, "mandatory")) goto l60;  yyDo(yy, yy_1_Requirements, yy->__begin, yy->__end);  goto l59;
  l60:;	  yy->__pos= yypos59; yy->__thunkpos= yythunkpos59;  if (!yy_IfDepends(yy)) goto l61;  yyDo(yy, yy_2_Requirements, yy->__begin, yy->__end);  goto l59;
  l61:;	  yy->__pos= yypos59; yy->__thunkpos= yythunkpos59;  if (!yy_OptDepends(yy)) goto l62;  yyDo(yy, yy_3_Requirements, yy->__begin, yy->__end);  goto l59;
  l62:;	  yy->__pos= yypos59; yy->__thunkpos= yythunkpos59;  if (!yymatchString(yy, "optional")) goto l63;  yyDo(yy, yy_4_Requirements, yy->__begin, yy->__end);  goto l59;
  l63:;	  yy->__pos= yypos59; yy->__thunkpos= yythunkpos59;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l58;
#undef yytext
#undef yyleng
  }  if (!yy_MiscUntilEOL(yy)) goto l58;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l58;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_5_Requirements, yy->__begin, yy->__end);
  }
  l59:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "Requirements", yy->__buf+yy->__pos));
  return 1;
  l58:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Requirements", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_Semicolon(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "Semicolon"));
  {  int yypos65= yy->__pos, yythunkpos65= yy->__thunkpos;  if (!yymatchChar(yy, ';')) goto l66;
  l67:;	
  {  int yypos68= yy->__pos, yythunkpos68= yy->__thunkpos;  if (!yy_Space(yy)) goto l68;  goto l67;
  l68:;	  yy->__pos= yypos68; yy->__thunkpos= yythunkpos68;
  }  goto l65;
  l66:;	  yy->__pos= yypos65; yy->__thunkpos= yythunkpos65;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l64;
#undef yytext
#undef yyleng
  }  if (!yy_MiscUntilEOL(yy)) goto l64;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l64;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_1_Semicolon, yy->__begin, yy->__end);
  }
  l65:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "Semicolon", yy->__buf+yy->__pos));
  return 1;
  l64:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Semicolon", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_Tag(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "Tag"));  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l69;
#undef yytext
#undef yyleng
  }  if (!yy_Number(yy)) goto l69;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l69;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_1_Tag, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "Tag", yy->__buf+yy->__pos));
  return 1;
  l69:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Tag", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_Colon(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "Colon"));
  {  int yypos71= yy->__pos, yythunkpos71= yy->__thunkpos;  if (!yymatchChar(yy, ',')) goto l72;
  l73:;	
  {  int yypos74= yy->__pos, yythunkpos74= yy->__thunkpos;  if (!yy_Space(yy)) goto l74;  goto l73;
  l74:;	  yy->__pos= yypos74; yy->__thunkpos= yythunkpos74;
  }  goto l71;
  l72:;	  yy->__pos= yypos71; yy->__thunkpos= yythunkpos71;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l70;
#undef yytext
#undef yyleng
  }  if (!yy_MiscUntilEOL(yy)) goto l70;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l70;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_1_Colon, yy->__begin, yy->__end);
  }
  l71:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "Colon", yy->__buf+yy->__pos));
  return 1;
  l70:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Colon", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_PrintableAscii(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "PrintableAscii"));  if (!yymatchString(yy, "printascii")) goto l75;
  yyprintf((stderr, "  ok   %s @ %s\n", "PrintableAscii", yy->__buf+yy->__pos));
  return 1;
  l75:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "PrintableAscii", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_RegEx(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "RegEx"));
  {  int yypos77= yy->__pos, yythunkpos77= yy->__thunkpos;  if (!yymatchString(yy, "regex")) goto l78;  if (!yy_OpenBracket(yy)) goto l78;  if (!yymatchChar(yy, '"')) goto l78;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l78;
#undef yytext
#undef yyleng
  }
  l79:;	
  {  int yypos80= yy->__pos, yythunkpos80= yy->__thunkpos;  if (!yy_PCRE(yy)) goto l80;  goto l79;
  l80:;	  yy->__pos= yypos80; yy->__thunkpos= yythunkpos80;
  }  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l78;
#undef yytext
#undef yyleng
  }  if (!yymatchChar(yy, '"')) goto l78;  if (!yy_ClosingBracket(yy)) goto l78;  yyDo(yy, yy_1_RegEx, yy->__begin, yy->__end);  goto l77;
  l78:;	  yy->__pos= yypos77; yy->__thunkpos= yythunkpos77;  if (!yymatchString(yy, "regex")) goto l81;  if (!yy_OpenBracket(yy)) goto l81;  if (!yymatchChar(yy, '"')) goto l81;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l81;
#undef yytext
#undef yyleng
  }
  l82:;	
  {  int yypos83= yy->__pos, yythunkpos83= yy->__thunkpos;  if (!yy_PCRE(yy)) goto l83;  goto l82;
  l83:;	  yy->__pos= yypos83; yy->__thunkpos= yythunkpos83;
  }  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l81;
#undef yytext
#undef yyleng
  }  if (!yymatchChar(yy, '"')) goto l81;  yyDo(yy, yy_2_RegEx, yy->__begin, yy->__end);  goto l77;
  l81:;	  yy->__pos= yypos77; yy->__thunkpos= yythunkpos77;  if (!yymatchString(yy, "regex")) goto l84;  if (!yy_OpenBracket(yy)) goto l84;  if (!yymatchChar(yy, '"')) goto l84;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l84;
#undef yytext
#undef yyleng
  }
  l85:;	
  {  int yypos86= yy->__pos, yythunkpos86= yy->__thunkpos;  if (!yy_PCRE(yy)) goto l86;  goto l85;
  l86:;	  yy->__pos= yypos86; yy->__thunkpos= yythunkpos86;
  }  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l84;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_3_RegEx, yy->__begin, yy->__end);  goto l77;
  l84:;	  yy->__pos= yypos77; yy->__thunkpos= yythunkpos77;  if (!yymatchString(yy, "regex")) goto l87;  if (!yy_OpenBracket(yy)) goto l87;  if (!yymatchChar(yy, '"')) goto l87;  yyDo(yy, yy_4_RegEx, yy->__begin, yy->__end);  goto l77;
  l87:;	  yy->__pos= yypos77; yy->__thunkpos= yythunkpos77;  if (!yymatchString(yy, "regex")) goto l88;  if (!yy_OpenBracket(yy)) goto l88;  yyDo(yy, yy_5_RegEx, yy->__begin, yy->__end);  goto l77;
  l88:;	  yy->__pos= yypos77; yy->__thunkpos= yythunkpos77;  if (!yymatchString(yy, "regex")) goto l76;  yyDo(yy, yy_6_RegEx, yy->__begin, yy->__end);
  }
  l77:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "RegEx", yy->__buf+yy->__pos));
  return 1;
  l76:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "RegEx", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_NTupel(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "NTupel"));
  {  int yypos90= yy->__pos, yythunkpos90= yy->__thunkpos;  if (!yymatchString(yy, "ntupel")) goto l91;  if (!yy_OpenBracket(yy)) goto l91;  if (!yy_ValueList(yy)) goto l91;  if (!yy_ClosingBracket(yy)) goto l91;  yyDo(yy, yy_1_NTupel, yy->__begin, yy->__end);  goto l90;
  l91:;	  yy->__pos= yypos90; yy->__thunkpos= yythunkpos90;  if (!yymatchString(yy, "ntupel")) goto l92;  if (!yy_OpenBracket(yy)) goto l92;  if (!yy_ValueList(yy)) goto l92;  yyDo(yy, yy_2_NTupel, yy->__begin, yy->__end);  goto l90;
  l92:;	  yy->__pos= yypos90; yy->__thunkpos= yythunkpos90;  if (!yymatchString(yy, "ntupel")) goto l93;  if (!yy_OpenBracket(yy)) goto l93;  yyDo(yy, yy_3_NTupel, yy->__begin, yy->__end);  goto l90;
  l93:;	  yy->__pos= yypos90; yy->__thunkpos= yythunkpos90;  if (!yymatchString(yy, "ntupel")) goto l89;  yyDo(yy, yy_4_NTupel, yy->__begin, yy->__end);
  }
  l90:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "NTupel", yy->__buf+yy->__pos));
  return 1;
  l89:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "NTupel", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_Number(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "Number"));
  {  int yypos95= yy->__pos, yythunkpos95= yy->__thunkpos;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l96;
#undef yytext
#undef yyleng
  }  if (!yymatchString(yy, "0x")) goto l96;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\176\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l96;
  l97:;	
  {  int yypos98= yy->__pos, yythunkpos98= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\176\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l98;  goto l97;
  l98:;	  yy->__pos= yypos98; yy->__thunkpos= yythunkpos98;
  }  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l96;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_1_Number, yy->__begin, yy->__end);  goto l95;
  l96:;	  yy->__pos= yypos95; yy->__thunkpos= yythunkpos95;  if (!yymatchString(yy, "2^")) goto l99;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l99;
#undef yytext
#undef yyleng
  }  if (!yy_Digit(yy)) goto l99;
  l100:;	
  {  int yypos101= yy->__pos, yythunkpos101= yy->__thunkpos;  if (!yy_Digit(yy)) goto l101;  goto l100;
  l101:;	  yy->__pos= yypos101; yy->__thunkpos= yythunkpos101;
  }  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l99;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_2_Number, yy->__begin, yy->__end);  goto l95;
  l99:;	  yy->__pos= yypos95; yy->__thunkpos= yythunkpos95;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l94;
#undef yytext
#undef yyleng
  }  if (!yy_Digit(yy)) goto l94;
  l102:;	
  {  int yypos103= yy->__pos, yythunkpos103= yy->__thunkpos;  if (!yy_Digit(yy)) goto l103;  goto l102;
  l103:;	  yy->__pos= yypos103; yy->__thunkpos= yythunkpos103;
  }  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l94;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_3_Number, yy->__begin, yy->__end);
  }
  l95:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "Number", yy->__buf+yy->__pos));
  return 1;
  l94:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Number", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_Only(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "Only"));
  {  int yypos105= yy->__pos, yythunkpos105= yy->__thunkpos;  if (!yymatchString(yy, "only")) goto l106;  if (!yy_OpenBracket(yy)) goto l106;  if (!yy_Number(yy)) goto l106;  if (!yy_ClosingBracket(yy)) goto l106;  yyDo(yy, yy_1_Only, yy->__begin, yy->__end);  goto l105;
  l106:;	  yy->__pos= yypos105; yy->__thunkpos= yythunkpos105;  if (!yymatchString(yy, "only")) goto l107;  if (!yy_OpenBracket(yy)) goto l107;  if (!yy_Number(yy)) goto l107;  yyDo(yy, yy_2_Only, yy->__begin, yy->__end);  goto l105;
  l107:;	  yy->__pos= yypos105; yy->__thunkpos= yythunkpos105;  if (!yymatchString(yy, "only")) goto l108;  if (!yy_OpenBracket(yy)) goto l108;  yyDo(yy, yy_3_Only, yy->__begin, yy->__end);  goto l105;
  l108:;	  yy->__pos= yypos105; yy->__thunkpos= yythunkpos105;  if (!yymatchString(yy, "only")) goto l104;  yyDo(yy, yy_4_Only, yy->__begin, yy->__end);
  }
  l105:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "Only", yy->__buf+yy->__pos));
  return 1;
  l104:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Only", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_Range(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "Range"));
  {  int yypos110= yy->__pos, yythunkpos110= yy->__thunkpos;  if (!yymatchString(yy, "range")) goto l111;  if (!yy_OpenBracket(yy)) goto l111;  if (!yy_Number(yy)) goto l111;  if (!yy_Colon(yy)) goto l111;  if (!yy_Number(yy)) goto l111;  if (!yy_ClosingBracket(yy)) goto l111;  goto l110;
  l111:;	  yy->__pos= yypos110; yy->__thunkpos= yythunkpos110;  if (!yymatchString(yy, "range")) goto l112;  if (!yy_OpenBracket(yy)) goto l112;  if (!yy_Number(yy)) goto l112;  if (!yy_Colon(yy)) goto l112;  if (!yy_Number(yy)) goto l112;  yyDo(yy, yy_1_Range, yy->__begin, yy->__end);  goto l110;
  l112:;	  yy->__pos= yypos110; yy->__thunkpos= yythunkpos110;  if (!yymatchString(yy, "range")) goto l113;  if (!yy_OpenBracket(yy)) goto l113;  if (!yy_Number(yy)) goto l113;  if (!yy_Colon(yy)) goto l113;  yyDo(yy, yy_2_Range, yy->__begin, yy->__end);  goto l110;
  l113:;	  yy->__pos= yypos110; yy->__thunkpos= yythunkpos110;  if (!yymatchString(yy, "range")) goto l114;  if (!yy_OpenBracket(yy)) goto l114;  if (!yy_Number(yy)) goto l114;  yyDo(yy, yy_3_Range, yy->__begin, yy->__end);  goto l110;
  l114:;	  yy->__pos= yypos110; yy->__thunkpos= yythunkpos110;  if (!yymatchString(yy, "range")) goto l115;  if (!yy_OpenBracket(yy)) goto l115;  yyDo(yy, yy_4_Range, yy->__begin, yy->__end);  goto l110;
  l115:;	  yy->__pos= yypos110; yy->__thunkpos= yythunkpos110;  if (!yymatchString(yy, "range")) goto l109;  yyDo(yy, yy_5_Range, yy->__begin, yy->__end);
  }
  l110:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "Range", yy->__buf+yy->__pos));
  return 1;
  l109:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Range", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_Any(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "Any"));  if (!yymatchString(yy, "any")) goto l116;
  yyprintf((stderr, "  ok   %s @ %s\n", "Any", yy->__buf+yy->__pos));
  return 1;
  l116:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Any", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_LogicalOrListElement(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "LogicalOrListElement"));
  {  int yypos118= yy->__pos, yythunkpos118= yy->__thunkpos;  if (!yy_Any(yy)) goto l119;  yyDo(yy, yy_1_LogicalOrListElement, yy->__begin, yy->__end);  goto l118;
  l119:;	  yy->__pos= yypos118; yy->__thunkpos= yythunkpos118;  if (!yy_Range(yy)) goto l120;  yyDo(yy, yy_2_LogicalOrListElement, yy->__begin, yy->__end);  goto l118;
  l120:;	  yy->__pos= yypos118; yy->__thunkpos= yythunkpos118;  if (!yy_Only(yy)) goto l121;  yyDo(yy, yy_3_LogicalOrListElement, yy->__begin, yy->__end);  goto l118;
  l121:;	  yy->__pos= yypos118; yy->__thunkpos= yythunkpos118;  if (!yy_Number(yy)) goto l122;  yyDo(yy, yy_4_LogicalOrListElement, yy->__begin, yy->__end);  goto l118;
  l122:;	  yy->__pos= yypos118; yy->__thunkpos= yythunkpos118;  if (!yy_NTupel(yy)) goto l123;  yyDo(yy, yy_5_LogicalOrListElement, yy->__begin, yy->__end);  goto l118;
  l123:;	  yy->__pos= yypos118; yy->__thunkpos= yythunkpos118;  if (!yy_RegEx(yy)) goto l124;  yyDo(yy, yy_6_LogicalOrListElement, yy->__begin, yy->__end);  goto l118;
  l124:;	  yy->__pos= yypos118; yy->__thunkpos= yythunkpos118;  if (!yy_PrintableAscii(yy)) goto l125;  yyDo(yy, yy_7_LogicalOrListElement, yy->__begin, yy->__end);  goto l118;
  l125:;	  yy->__pos= yypos118; yy->__thunkpos= yythunkpos118;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l117;
#undef yytext
#undef yyleng
  }  if (!yy_MiscUntilEOL(yy)) goto l117;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l117;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_8_LogicalOrListElement, yy->__begin, yy->__end);
  }
  l118:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "LogicalOrListElement", yy->__buf+yy->__pos));
  return 1;
  l117:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "LogicalOrListElement", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_LogicalOrList(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "LogicalOrList"));  if (!yy_LogicalOrListElement(yy)) goto l126;
  l127:;	
  {  int yypos128= yy->__pos, yythunkpos128= yy->__thunkpos;  if (!yy_Colon(yy)) goto l128;  if (!yy_LogicalOrListElement(yy)) goto l128;  goto l127;
  l128:;	  yy->__pos= yypos128; yy->__thunkpos= yythunkpos128;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "LogicalOrList", yy->__buf+yy->__pos));
  return 1;
  l126:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "LogicalOrList", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_LogicalOr(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "LogicalOr"));  if (!yymatchString(yy, "logical_or")) goto l129;  if (!yy_OpenBracket(yy)) goto l129;  if (!yy_LogicalOrList(yy)) goto l129;  if (!yy_ClosingBracket(yy)) goto l129;  yyDo(yy, yy_1_LogicalOr, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "LogicalOr", yy->__buf+yy->__pos));
  return 1;
  l129:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "LogicalOr", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_Mode(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "Mode"));
  {  int yypos131= yy->__pos, yythunkpos131= yy->__thunkpos;  if (!yymatchString(yy, "baseline")) goto l132;  yyDo(yy, yy_1_Mode, yy->__begin, yy->__end);  goto l131;
  l132:;	  yy->__pos= yypos131; yy->__thunkpos= yythunkpos131;  if (!yymatchString(yy, "enable_type_checks")) goto l133;  yyDo(yy, yy_2_Mode, yy->__begin, yy->__end);  goto l131;
  l133:;	  yy->__pos= yypos131; yy->__thunkpos= yythunkpos131;  if (!yymatchString(yy, "enable_offset_checks")) goto l134;  yyDo(yy, yy_3_Mode, yy->__begin, yy->__end);  goto l131;
  l134:;	  yy->__pos= yypos131; yy->__thunkpos= yythunkpos131;  if (!yymatchString(yy, "enable_ifd_checks")) goto l135;  yyDo(yy, yy_4_Mode, yy->__begin, yy->__end);  goto l131;
  l135:;	  yy->__pos= yypos131; yy->__thunkpos= yythunkpos131;  if (!yymatchString(yy, "enhanced")) goto l136;  goto l131;
  l136:;	  yy->__pos= yypos131; yy->__thunkpos= yythunkpos131;  if (!yy_MiscUntilEOL(yy)) goto l130;  yyDo(yy, yy_5_Mode, yy->__begin, yy->__end);
  }
  l131:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "Mode", yy->__buf+yy->__pos));
  return 1;
  l130:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Mode", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_ClosingBracket(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "ClosingBracket"));  if (!yymatchChar(yy, ')')) goto l137;
  yyprintf((stderr, "  ok   %s @ %s\n", "ClosingBracket", yy->__buf+yy->__pos));
  return 1;
  l137:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "ClosingBracket", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_OpenBracket(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "OpenBracket"));  if (!yymatchChar(yy, '(')) goto l138;
  yyprintf((stderr, "  ok   %s @ %s\n", "OpenBracket", yy->__buf+yy->__pos));
  return 1;
  l138:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "OpenBracket", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_MiscUntilEOL(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "MiscUntilEOL"));  if (!yymatchClass(yy, (unsigned char *)"\377\333\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377")) goto l139;
  l140:;	
  {  int yypos141= yy->__pos, yythunkpos141= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\377\333\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377")) goto l141;  goto l140;
  l141:;	  yy->__pos= yypos141; yy->__thunkpos= yythunkpos141;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "MiscUntilEOL", yy->__buf+yy->__pos));
  return 1;
  l139:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "MiscUntilEOL", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_TagLine(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "TagLine"));
  {  int yypos143= yy->__pos, yythunkpos143= yy->__thunkpos;  if (!yy_Tag(yy)) goto l144;  if (!yy_Semicolon(yy)) goto l144;  if (!yy_Requirements(yy)) goto l144;  if (!yy_Semicolon(yy)) goto l144;  if (!yy_Content(yy)) goto l144;  yyDo(yy, yy_1_TagLine, yy->__begin, yy->__end);  goto l143;
  l144:;	  yy->__pos= yypos143; yy->__thunkpos= yythunkpos143;  if (!yy_Tag(yy)) goto l145;  if (!yy_Semicolon(yy)) goto l145;  if (!yy_Requirements(yy)) goto l145;  if (!yy_Semicolon(yy)) goto l145;  yyDo(yy, yy_2_TagLine, yy->__begin, yy->__end);  goto l143;
  l145:;	  yy->__pos= yypos143; yy->__thunkpos= yythunkpos143;  if (!yy_Tag(yy)) goto l146;  if (!yy_Semicolon(yy)) goto l146;  if (!yy_Requirements(yy)) goto l146;  yyDo(yy, yy_3_TagLine, yy->__begin, yy->__end);  goto l143;
  l146:;	  yy->__pos= yypos143; yy->__thunkpos= yythunkpos143;  if (!yy_Tag(yy)) goto l147;  if (!yy_Semicolon(yy)) goto l147;  yyDo(yy, yy_4_TagLine, yy->__begin, yy->__end);  goto l143;
  l147:;	  yy->__pos= yypos143; yy->__thunkpos= yythunkpos143;  if (!yy_Tag(yy)) goto l142;  yyDo(yy, yy_5_TagLine, yy->__begin, yy->__end);
  }
  l143:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "TagLine", yy->__buf+yy->__pos));
  return 1;
  l142:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "TagLine", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_IncludeLine(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "IncludeLine"));  if (!yymatchString(yy, "include")) goto l148;  if (!yy_OpenBracket(yy)) goto l148;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l148;
#undef yytext
#undef yyleng
  }  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\340\377\003\376\377\377\207\376\377\377\007\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l148;
  l149:;	
  {  int yypos150= yy->__pos, yythunkpos150= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\340\377\003\376\377\377\207\376\377\377\007\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l150;  goto l149;
  l150:;	  yy->__pos= yypos150; yy->__thunkpos= yythunkpos150;
  }  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l148;
#undef yytext
#undef yyleng
  }  if (!yy_ClosingBracket(yy)) goto l148;  yyDo(yy, yy_1_IncludeLine, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "IncludeLine", yy->__buf+yy->__pos));
  return 1;
  l148:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "IncludeLine", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_ModeLine(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "ModeLine"));
  {  int yypos152= yy->__pos, yythunkpos152= yy->__thunkpos;  if (!yymatchString(yy, "mode")) goto l153;  if (!yy_OpenBracket(yy)) goto l153;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l153;
#undef yytext
#undef yyleng
  }  if (!yy_Mode(yy)) goto l153;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l153;
#undef yytext
#undef yyleng
  }  if (!yy_ClosingBracket(yy)) goto l153;  yyDo(yy, yy_1_ModeLine, yy->__begin, yy->__end);  goto l152;
  l153:;	  yy->__pos= yypos152; yy->__thunkpos= yythunkpos152;  if (!yymatchString(yy, "mode")) goto l154;  if (!yy_OpenBracket(yy)) goto l154;  if (!yy_Mode(yy)) goto l154;  yyDo(yy, yy_2_ModeLine, yy->__begin, yy->__end);  goto l152;
  l154:;	  yy->__pos= yypos152; yy->__thunkpos= yythunkpos152;  if (!yymatchString(yy, "mode")) goto l155;  if (!yy_OpenBracket(yy)) goto l155;  yyDo(yy, yy_3_ModeLine, yy->__begin, yy->__end);  goto l152;
  l155:;	  yy->__pos= yypos152; yy->__thunkpos= yythunkpos152;  if (!yymatchString(yy, "mode")) goto l151;  yyDo(yy, yy_4_ModeLine, yy->__begin, yy->__end);
  }
  l152:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "ModeLine", yy->__buf+yy->__pos));
  return 1;
  l151:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "ModeLine", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_SpaceLine(yycontext *yy)
{
  yyprintf((stderr, "%s\n", "SpaceLine"));
  l157:;	
  {  int yypos158= yy->__pos, yythunkpos158= yy->__thunkpos;  if (!yy_Space(yy)) goto l158;  goto l157;
  l158:;	  yy->__pos= yypos158; yy->__thunkpos= yythunkpos158;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "SpaceLine", yy->__buf+yy->__pos));
  return 1;
}
YY_RULE(int) yy_EndOfLine(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "EndOfLine"));  if (!yymatchClass(yy, (unsigned char *)"\000\044\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l159;  yyDo(yy, yy_1_EndOfLine, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "EndOfLine", yy->__buf+yy->__pos));
  return 1;
  l159:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "EndOfLine", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_CommentLine(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "CommentLine"));  if (!yymatchChar(yy, '#')) goto l160;
  l161:;	
  {  int yypos162= yy->__pos, yythunkpos162= yy->__thunkpos;
  {  int yypos163= yy->__pos, yythunkpos163= yy->__thunkpos;  if (!yy_EndOfLine(yy)) goto l163;  goto l162;
  l163:;	  yy->__pos= yypos163; yy->__thunkpos= yythunkpos163;
  }  if (!yymatchDot(yy)) goto l162;  goto l161;
  l162:;	  yy->__pos= yypos162; yy->__thunkpos= yythunkpos162;
  }  yyDo(yy, yy_1_CommentLine, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "CommentLine", yy->__buf+yy->__pos));
  return 1;
  l160:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "CommentLine", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_EndOfFile(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "EndOfFile"));
  {  int yypos165= yy->__pos, yythunkpos165= yy->__thunkpos;  if (!yymatchDot(yy)) goto l165;  goto l164;
  l165:;	  yy->__pos= yypos165; yy->__thunkpos= yythunkpos165;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "EndOfFile", yy->__buf+yy->__pos));
  return 1;
  l164:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "EndOfFile", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_Line(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "Line"));
  {  int yypos167= yy->__pos, yythunkpos167= yy->__thunkpos;  if (!yy_CommentLine(yy)) goto l168;  if (!yy_EndOfLine(yy)) goto l168;  goto l167;
  l168:;	  yy->__pos= yypos167; yy->__thunkpos= yythunkpos167;  if (!yy_SpaceLine(yy)) goto l169;  if (!yy_EndOfLine(yy)) goto l169;  goto l167;
  l169:;	  yy->__pos= yypos167; yy->__thunkpos= yythunkpos167;  if (!yy_ModeLine(yy)) goto l170;  if (!yy_EndOfLine(yy)) goto l170;  goto l167;
  l170:;	  yy->__pos= yypos167; yy->__thunkpos= yythunkpos167;  if (!yy_IncludeLine(yy)) goto l171;  if (!yy_EndOfLine(yy)) goto l171;  goto l167;
  l171:;	  yy->__pos= yypos167; yy->__thunkpos= yythunkpos167;  if (!yy_TagLine(yy)) goto l172;  if (!yy_EndOfLine(yy)) goto l172;  goto l167;
  l172:;	  yy->__pos= yypos167; yy->__thunkpos= yythunkpos167;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l166;
#undef yytext
#undef yyleng
  }  if (!yy_MiscUntilEOL(yy)) goto l166;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l166;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_1_Line, yy->__begin, yy->__end);
  }
  l167:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "Line", yy->__buf+yy->__pos));
  return 1;
  l166:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Line", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_start(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "start"));  if (!yy_Line(yy)) goto l173;
  l174:;	
  {  int yypos175= yy->__pos, yythunkpos175= yy->__thunkpos;  if (!yy_Line(yy)) goto l175;  goto l174;
  l175:;	  yy->__pos= yypos175; yy->__thunkpos= yythunkpos175;
  }  if (!yy_EndOfFile(yy)) goto l173;
  yyprintf((stderr, "  ok   %s @ %s\n", "start", yy->__buf+yy->__pos));
  return 1;
  l173:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "start", yy->__buf+yy->__pos));
  return 0;
}

#ifndef YY_PART

typedef int (*yyrule)(yycontext *yy);

YY_PARSE(int) YYPARSEFROM(YY_CTX_PARAM_ yyrule yystart)
{
  int yyok;
  if (!yyctx->__buflen)
    {
      yyctx->__buflen= YY_BUFFER_SIZE;
      yyctx->__buf= (char *)YY_MALLOC(yyctx, yyctx->__buflen);
      yyctx->__textlen= YY_BUFFER_SIZE;
      yyctx->__text= (char *)YY_MALLOC(yyctx, yyctx->__textlen);
      yyctx->__thunkslen= YY_STACK_SIZE;
      yyctx->__thunks= (yythunk *)YY_MALLOC(yyctx, sizeof(yythunk) * yyctx->__thunkslen);
      yyctx->__valslen= YY_STACK_SIZE;
      yyctx->__vals= (YYSTYPE *)YY_MALLOC(yyctx, sizeof(YYSTYPE) * yyctx->__valslen);
      yyctx->__begin= yyctx->__end= yyctx->__pos= yyctx->__limit= yyctx->__thunkpos= 0;
    }
  yyctx->__begin= yyctx->__end= yyctx->__pos;
  yyctx->__thunkpos= 0;
  yyctx->__val= yyctx->__vals;
  yyok= yystart(yyctx);
  if (yyok) yyDone(yyctx);
  yyCommit(yyctx);
  return yyok;
}

YY_PARSE(int) YYPARSE(YY_CTX_PARAM)
{
  return YYPARSEFROM(YY_CTX_ARG_ yy_start);
}

YY_PARSE(yycontext *) YYRELEASE(yycontext *yyctx)
{
  if (yyctx->__buflen)
    {
      yyctx->__buflen= 0;
      YY_FREE(yyctx, yyctx->__buf);
      YY_FREE(yyctx, yyctx->__text);
      YY_FREE(yyctx, yyctx->__thunks);
      YY_FREE(yyctx, yyctx->__vals);
    }
  return yyctx;
}

#endif
